/**
 * This is a worker script for dotlottie.
 * Do not modify this file directly.
 * As it's generated by the build process.
 */

var qi = Object.defineProperty;
var Gi = (v, o, a) => (o in v ? qi(v, o, { enumerable: !0, configurable: !0, writable: !0, value: a }) : (v[o] = a));
var L = (v, o, a) => Gi(v, typeof o != 'symbol' ? o + '' : o, a);
var ot = class {
    requestAnimationFrame(o) {
      return requestAnimationFrame(o);
    }
    cancelAnimationFrame(o) {
      cancelAnimationFrame(o);
    }
  },
  st = class {
    constructor() {
      L(this, '_lastHandleId', 0);
      L(this, '_lastImmediate', null);
    }
    requestAnimationFrame(o) {
      return (
        this._lastHandleId >= Number.MAX_SAFE_INTEGER && (this._lastHandleId = 0),
        (this._lastHandleId += 1),
        (this._lastImmediate = setImmediate(() => {
          o(Date.now());
        })),
        this._lastHandleId
      );
    }
    cancelAnimationFrame(o) {
      this._lastImmediate && clearImmediate(this._lastImmediate);
    }
  },
  Ie = class {
    constructor() {
      L(this, '_strategy');
      this._strategy = typeof requestAnimationFrame == 'function' ? new ot() : new st();
    }
    requestAnimationFrame(o) {
      return this._strategy.requestAnimationFrame(o);
    }
    cancelAnimationFrame(o) {
      this._strategy.cancelAnimationFrame(o);
    }
  };
var at = typeof window < 'u' && typeof window.document < 'u';
var Ce = {
  name: '@lottiefiles/dotlottie-web',
  version: '0.23.2',
  type: 'module',
  description: 'Lottie and DotLottie player for the web',
  repository: { type: 'git', url: 'git+https://github.com/LottieFiles/dotlottie-web.git', directory: 'packages/web' },
  homepage: 'https://github.com/LottieFiles/dotlottie-web#readme',
  bugs: 'https://github.com/LottieFiles/dotlottie-web/issues',
  author: 'LottieFiles',
  contributors: ['Abdelrahman Ashraf <a.theashraf@gmail.com>'],
  license: 'MIT',
  main: 'dist/index.cjs',
  module: 'dist/index.js',
  types: 'dist/index.d.ts',
  files: ['dist'],
  keywords: ['dotlottie', 'lottie', 'player', 'animation', 'web', 'canvas', 'javascript', 'thorvg'],
  scripts: {
    build: 'tsup',
    dev: 'tsup --watch',
    lint: 'eslint --fix .',
    'stats:eslint': 'cross-env TIMING=1 eslint .',
    'stats:ts': 'tsc -p tsconfig.build.json --extendedDiagnostics',
    test: 'vitest run --browser.headless',
    'test:coverage': 'vitest run --browser.headless --coverage',
    'test:watch': 'vitest',
    'type-check': 'tsc --noEmit',
  },
  devDependencies: {
    '@types/node': '^20.10.5',
    '@vitest/browser': '^1.2.2 ',
    '@vitest/coverage-istanbul': '^1.2.2',
    'cross-env': '7.0.3',
    tsup: '8.1.0',
    typescript: '5.0.4',
    vitest: '^1.2.2',
    webdriverio: '^8.32.0',
  },
  publishConfig: { access: 'public' },
};
var Ji = (() => {
    let v = typeof document < 'u' ? document.currentScript?.src : void 0;
    return function (o = {}) {
      let a = o,
        _,
        m,
        k = new Promise((e, t) => {
          (_ = e), (m = t);
        }),
        b = { ...a },
        J = './this.program',
        Ee = !0,
        V = '';
      function tn(e) {
        return a.locateFile ? a.locateFile(e, V) : V + e;
      }
      typeof document < 'u' && document.currentScript && (V = document.currentScript.src),
        v && (V = v),
        V.startsWith('blob:') ? (V = '') : (V = V.substr(0, V.replace(/[#?].*/, '').lastIndexOf('/') + 1)),
        (e, t, n) => {
          let r = new XMLHttpRequest();
          r.open('GET', e, !0),
            (r.responseType = 'arraybuffer'),
            (r.onload = () => {
              if (r.status == 200 || (r.status == 0 && r.response)) {
                t(r.response);
                return;
              }
              n();
            }),
            (r.onerror = n),
            r.send(null);
        };
      let on = a.print || console.log.bind(console),
        ie = a.printErr || console.error.bind(console);
      Object.assign(a, b),
        (b = null),
        a.arguments && a.arguments,
        a.thisProgram && (J = a.thisProgram),
        a.quit && a.quit;
      let ue;
      a.wasmBinary && (ue = a.wasmBinary);
      let Te,
        ft = !1,
        H,
        P,
        oe,
        de,
        S,
        T,
        pt,
        ht;
      function mt() {
        let e = Te.buffer;
        (a.HEAP8 = H = new Int8Array(e)),
          (a.HEAP16 = oe = new Int16Array(e)),
          (a.HEAPU8 = P = new Uint8Array(e)),
          (a.HEAPU16 = de = new Uint16Array(e)),
          (a.HEAP32 = S = new Int32Array(e)),
          (a.HEAPU32 = T = new Uint32Array(e)),
          (a.HEAPF32 = pt = new Float32Array(e)),
          (a.HEAPF64 = ht = new Float64Array(e));
      }
      let _t = [],
        gt = [],
        yt = [];
      function cn() {
        if (a.preRun)
          for (typeof a.preRun == 'function' && (a.preRun = [a.preRun]); a.preRun.length; ) dn(a.preRun.shift());
        Be(_t);
      }
      function ln() {
        Be(gt);
      }
      function un() {
        if (a.postRun)
          for (typeof a.postRun == 'function' && (a.postRun = [a.postRun]); a.postRun.length; ) pn(a.postRun.shift());
        Be(yt);
      }
      function dn(e) {
        _t.unshift(e);
      }
      function fn(e) {
        gt.unshift(e);
      }
      function pn(e) {
        yt.unshift(e);
      }
      let K = 0,
        fe = null;
      function hn(e) {
        K++, a.monitorRunDependencies?.(K);
      }
      function mn(e) {
        if ((K--, a.monitorRunDependencies?.(K), K == 0 && fe)) {
          let t = fe;
          (fe = null), t();
        }
      }
      function Fe(e) {
        a.onAbort?.(e), (e = `Aborted(${e})`), ie(e), (ft = !0), (e += '. Build with -sASSERTIONS for more info.');
        let t = new WebAssembly.RuntimeError(e);
        throw (m(t), t);
      }
      let _n = 'data:application/octet-stream;base64,',
        vt = (e) => e.startsWith(_n),
        se;
      (se = 'DotLottiePlayer.wasm'), vt(se) || (se = tn(se));
      function bt(e) {
        if (e == se && ue) return new Uint8Array(ue);
        throw 'both async and sync fetching of the wasm failed';
      }
      function gn(e) {
        return !ue && Ee && typeof fetch == 'function'
          ? fetch(e, { credentials: 'same-origin' })
              .then((t) => {
                if (!t.ok) throw `failed to load wasm binary file at '${e}'`;
                return t.arrayBuffer();
              })
              .catch(() => bt(e))
          : Promise.resolve().then(() => bt(e));
      }
      function Ct(e, t, n) {
        return gn(e)
          .then((r) => WebAssembly.instantiate(r, t))
          .then(n, (r) => {
            ie(`failed to asynchronously prepare wasm: ${r}`), Fe(r);
          });
      }
      function yn(e, t, n, r) {
        return !e && typeof WebAssembly.instantiateStreaming == 'function' && !vt(t) && typeof fetch == 'function'
          ? fetch(t, { credentials: 'same-origin' }).then((i) =>
              WebAssembly.instantiateStreaming(i, n).then(r, function (l) {
                return (
                  ie(`wasm streaming compile failed: ${l}`),
                  ie('falling back to ArrayBuffer instantiation'),
                  Ct(t, n, r)
                );
              }),
            )
          : Ct(t, n, r);
      }
      function vn() {
        let e = { a: _i };
        function t(r, i) {
          return (E = r.exports), (Te = E.la), mt(), (xt = E.pa), fn(E.ma), mn(), E;
        }
        hn();
        function n(r) {
          t(r.instance);
        }
        if (a.instantiateWasm)
          try {
            return a.instantiateWasm(e, t);
          } catch (r) {
            ie(`Module.instantiateWasm callback failed with error: ${r}`), m(r);
          }
        return yn(ue, se, e, n).catch(m), {};
      }
      var Be = (e) => {
        for (; e.length > 0; ) e.shift()(a);
      };
      a.noExitRuntime || !0;
      let j = (e) => qt(e),
        W = () => Gt(),
        wt = typeof TextDecoder < 'u' ? new TextDecoder('utf8') : void 0,
        Et = (e, t, n) => {
          let r = t + n,
            i = t;
          for (; e[i] && !(i >= r); ) ++i;
          if (i - t > 16 && e.buffer && wt) return wt.decode(e.subarray(t, i));
          let s = '';
          for (; t < i; ) {
            let l = e[t++];
            if (!(l & 128)) {
              s += String.fromCharCode(l);
              continue;
            }
            let c = e[t++] & 63;
            if ((l & 224) == 192) {
              s += String.fromCharCode(((l & 31) << 6) | c);
              continue;
            }
            let u = e[t++] & 63;
            if (
              ((l & 240) == 224
                ? (l = ((l & 15) << 12) | (c << 6) | u)
                : (l = ((l & 7) << 18) | (c << 12) | (u << 6) | (e[t++] & 63)),
              l < 65536)
            )
              s += String.fromCharCode(l);
            else {
              let f = l - 65536;
              s += String.fromCharCode(55296 | (f >> 10), 56320 | (f & 1023));
            }
          }
          return s;
        },
        Q = (e, t) => (e ? Et(P, e, t) : ''),
        bn = (e, t, n, r) => {
          Fe(`Assertion failed: ${Q(e)}, at: ${[t ? Q(t) : 'unknown filename', n, r ? Q(r) : 'unknown function']}`);
        },
        ae = 0;
      class Tt {
        constructor(t) {
          (this.excPtr = t), (this.ptr = t - 24);
        }
        get_adjusted_ptr() {
          return T[(this.ptr + 16) >> 2];
        }
        get_caught() {
          return H[this.ptr + 12] != 0;
        }
        get_destructor() {
          return T[(this.ptr + 8) >> 2];
        }
        get_exception_ptr() {
          if (Jt(this.get_type())) return T[this.excPtr >> 2];
          let n = this.get_adjusted_ptr();
          return n !== 0 ? n : this.excPtr;
        }
        get_rethrown() {
          return H[this.ptr + 13] != 0;
        }
        get_type() {
          return T[(this.ptr + 4) >> 2];
        }
        set_adjusted_ptr(t) {
          T[(this.ptr + 16) >> 2] = t;
        }
        set_caught(t) {
          (t = t ? 1 : 0), (H[this.ptr + 12] = t);
        }
        set_destructor(t) {
          T[(this.ptr + 8) >> 2] = t;
        }
        set_rethrown(t) {
          (t = t ? 1 : 0), (H[this.ptr + 13] = t);
        }
        set_type(t) {
          T[(this.ptr + 4) >> 2] = t;
        }
        init(t, n) {
          this.set_adjusted_ptr(0), this.set_type(t), this.set_destructor(n);
        }
      }
      let Cn = (e) => {
          throw (ae || (ae = e), ae);
        },
        Me = (e) => Nt(e),
        wn = (e) => {
          let t = ae;
          if (!t) return Me(0), 0;
          let n = new Tt(t);
          n.set_adjusted_ptr(t);
          let r = n.get_type();
          if (!r) return Me(0), t;
          for (let i in e) {
            let s = e[i];
            if (s === 0 || s === r) break;
            let l = n.ptr + 16;
            if (Xt(s, r, l)) return Me(s), t;
          }
          return Me(r), t;
        },
        En = () => wn([]),
        Fn = (e, t, n) => {
          throw (new Tt(e).init(t, n), (ae = e), ae);
        };
      function Mn(e, t, n) {
        return 0;
      }
      let $n = (e, t) => {},
        Ft = (e) => {
          let t = 0;
          for (let n = 0; n < e.length; ++n) {
            let r = e.charCodeAt(n);
            r <= 127 ? t++ : r <= 2047 ? (t += 2) : r >= 55296 && r <= 57343 ? ((t += 4), ++n) : (t += 3);
          }
          return t;
        },
        Mt = (e, t, n, r) => {
          if (!(r > 0)) return 0;
          let i = n,
            s = n + r - 1;
          for (let l = 0; l < e.length; ++l) {
            let c = e.charCodeAt(l);
            if (c >= 55296 && c <= 57343) {
              let u = e.charCodeAt(++l);
              c = (65536 + ((c & 1023) << 10)) | (u & 1023);
            }
            if (c <= 127) {
              if (n >= s) break;
              t[n++] = c;
            } else if (c <= 2047) {
              if (n + 1 >= s) break;
              (t[n++] = 192 | (c >> 6)), (t[n++] = 128 | (c & 63));
            } else if (c <= 65535) {
              if (n + 2 >= s) break;
              (t[n++] = 224 | (c >> 12)), (t[n++] = 128 | ((c >> 6) & 63)), (t[n++] = 128 | (c & 63));
            } else {
              if (n + 3 >= s) break;
              (t[n++] = 240 | (c >> 18)),
                (t[n++] = 128 | ((c >> 12) & 63)),
                (t[n++] = 128 | ((c >> 6) & 63)),
                (t[n++] = 128 | (c & 63));
            }
          }
          return (t[n] = 0), n - i;
        },
        Ln = (e, t, n) => Mt(e, P, t, n),
        Pn = (e, t) => {};
      function An(e, t, n) {
        return 0;
      }
      let kn = (e, t, n, r) => {};
      function Sn(e, t, n, r) {}
      let Rn = (e, t) => {},
        $e = {},
        ze = (e) => {
          for (; e.length; ) {
            let t = e.pop();
            e.pop()(t);
          }
        };
      function pe(e) {
        return this.fromWireType(T[e >> 2]);
      }
      let ce = {},
        Z = {},
        Le = {},
        $t,
        Pe = (e) => {
          throw new $t(e);
        },
        X = (e, t, n) => {
          e.forEach(function (c) {
            Le[c] = t;
          });
          function r(c) {
            let u = n(c);
            u.length !== e.length && Pe('Mismatched type converter count');
            for (let f = 0; f < e.length; ++f) Y(e[f], u[f]);
          }
          let i = new Array(t.length),
            s = [],
            l = 0;
          t.forEach((c, u) => {
            Z.hasOwnProperty(c)
              ? (i[u] = Z[c])
              : (s.push(c),
                ce.hasOwnProperty(c) || (ce[c] = []),
                ce[c].push(() => {
                  (i[u] = Z[c]), ++l, l === s.length && r(i);
                }));
          }),
            s.length === 0 && r(i);
        },
        Dn = (e) => {
          let t = $e[e];
          delete $e[e];
          let n = t.rawConstructor,
            r = t.rawDestructor,
            i = t.fields,
            s = i.map((l) => l.getterReturnType).concat(i.map((l) => l.setterArgumentType));
          X([e], s, (l) => {
            let c = {};
            return (
              i.forEach((u, f) => {
                let p = u.fieldName,
                  w = l[f],
                  y = u.getter,
                  F = u.getterContext,
                  $ = l[f + i.length],
                  O = u.setter,
                  x = u.setterContext;
                c[p] = {
                  read: (B) => w.fromWireType(y(F, B)),
                  write: (B, d) => {
                    let h = [];
                    O(x, B, $.toWireType(h, d)), ze(h);
                  },
                };
              }),
              [
                {
                  name: t.name,
                  fromWireType: (u) => {
                    let f = {};
                    for (let p in c) f[p] = c[p].read(u);
                    return r(u), f;
                  },
                  toWireType: (u, f) => {
                    for (var p in c) if (!(p in f)) throw new TypeError(`Missing field: "${p}"`);
                    let w = n();
                    for (p in c) c[p].write(w, f[p]);
                    return u !== null && u.push(r, w), w;
                  },
                  argPackAdvance: N,
                  readValueFromPointer: pe,
                  destructorFunction: r,
                },
              ]
            );
          });
        },
        xn = (e, t, n, r, i) => {},
        In = () => {
          let e = new Array(256);
          for (let t = 0; t < 256; ++t) e[t] = String.fromCharCode(t);
          Lt = e;
        },
        Lt,
        A = (e) => {
          let t = '',
            n = e;
          for (; P[n]; ) t += Lt[P[n++]];
          return t;
        },
        le,
        C = (e) => {
          throw new le(e);
        };
      function jn(e, t, n = {}) {
        let r = t.name;
        if ((e || C(`type "${r}" must have a positive integer typeid pointer`), Z.hasOwnProperty(e))) {
          if (n.ignoreDuplicateRegistrations) return;
          C(`Cannot register type '${r}' twice`);
        }
        if (((Z[e] = t), delete Le[e], ce.hasOwnProperty(e))) {
          let i = ce[e];
          delete ce[e], i.forEach((s) => s());
        }
      }
      function Y(e, t, n = {}) {
        if (!('argPackAdvance' in t)) throw new TypeError('registerType registeredInstance requires argPackAdvance');
        return jn(e, t, n);
      }
      var N = 8;
      let Wn = (e, t, n, r) => {
          (t = A(t)),
            Y(e, {
              name: t,
              fromWireType(i) {
                return !!i;
              },
              toWireType(i, s) {
                return s ? n : r;
              },
              argPackAdvance: N,
              readValueFromPointer(i) {
                return this.fromWireType(P[i]);
              },
              destructorFunction: null,
            });
        },
        Un = (e) => ({
          count: e.count,
          deleteScheduled: e.deleteScheduled,
          preservePointerOnDelete: e.preservePointerOnDelete,
          ptr: e.ptr,
          ptrType: e.ptrType,
          smartPtr: e.smartPtr,
          smartPtrType: e.smartPtrType,
        }),
        Ve = (e) => {
          function t(n) {
            return n.$$.ptrType.registeredClass.name;
          }
          C(`${t(e)} instance already deleted`);
        },
        Ye = !1,
        Pt = (e) => {},
        On = (e) => {
          e.smartPtr ? e.smartPtrType.rawDestructor(e.smartPtr) : e.ptrType.registeredClass.rawDestructor(e.ptr);
        },
        At = (e) => {
          (e.count.value -= 1), e.count.value === 0 && On(e);
        };
      var kt = (e, t, n) => {
        if (t === n) return e;
        if (n.baseClass === void 0) return null;
        let r = kt(e, t, n.baseClass);
        return r === null ? null : n.downcast(r);
      };
      let St = {},
        Bn = () => Object.keys(_e).length,
        Hn = () => {
          let e = [];
          for (let t in _e) _e.hasOwnProperty(t) && e.push(_e[t]);
          return e;
        },
        he = [],
        Ne = () => {
          for (; he.length; ) {
            let e = he.pop();
            (e.$$.deleteScheduled = !1), e.delete();
          }
        },
        me,
        zn = (e) => {
          (me = e), he.length && me && me(Ne);
        },
        Vn = () => {
          (a.getInheritedInstanceCount = Bn),
            (a.getLiveInheritedInstances = Hn),
            (a.flushPendingDeletes = Ne),
            (a.setDelayFunction = zn);
        };
      var _e = {};
      let Yn = (e, t) => {
          for (t === void 0 && C('ptr should not be undefined'); e.baseClass; ) (t = e.upcast(t)), (e = e.baseClass);
          return t;
        },
        Nn = (e, t) => ((t = Yn(e, t)), _e[t]),
        Ae = (e, t) => {
          (!t.ptrType || !t.ptr) && Pe('makeClassHandle requires ptr and ptrType');
          let n = !!t.smartPtrType,
            r = !!t.smartPtr;
          return (
            n !== r && Pe('Both smartPtrType and smartPtr must be specified'),
            (t.count = { value: 1 }),
            ge(Object.create(e, { $$: { value: t, writable: !0 } }))
          );
        };
      function qn(e) {
        let t = this.getPointee(e);
        if (!t) return this.destructor(e), null;
        let n = Nn(this.registeredClass, t);
        if (n !== void 0) {
          if (n.$$.count.value === 0) return (n.$$.ptr = t), (n.$$.smartPtr = e), n.clone();
          {
            let u = n.clone();
            return this.destructor(e), u;
          }
        }
        function r() {
          return this.isSmartPointer
            ? Ae(this.registeredClass.instancePrototype, {
                ptrType: this.pointeeType,
                ptr: t,
                smartPtrType: this,
                smartPtr: e,
              })
            : Ae(this.registeredClass.instancePrototype, { ptrType: this, ptr: e });
        }
        let i = this.registeredClass.getActualType(t),
          s = St[i];
        if (!s) return r.call(this);
        let l;
        this.isConst ? (l = s.constPointerType) : (l = s.pointerType);
        let c = kt(t, this.registeredClass, l.registeredClass);
        return c === null
          ? r.call(this)
          : this.isSmartPointer
          ? Ae(l.registeredClass.instancePrototype, { ptrType: l, ptr: c, smartPtrType: this, smartPtr: e })
          : Ae(l.registeredClass.instancePrototype, { ptrType: l, ptr: c });
      }
      var ge = (e) =>
        typeof FinalizationRegistry > 'u'
          ? ((ge = (t) => t), e)
          : ((Ye = new FinalizationRegistry((t) => {
              At(t.$$);
            })),
            (ge = (t) => {
              let n = t.$$;
              if (!!n.smartPtr) {
                let i = { $$: n };
                Ye.register(t, i, t);
              }
              return t;
            }),
            (Pt = (t) => Ye.unregister(t)),
            ge(e));
      let Gn = () => {
        Object.assign(ke.prototype, {
          isAliasOf(e) {
            if (!(this instanceof ke) || !(e instanceof ke)) return !1;
            let t = this.$$.ptrType.registeredClass,
              n = this.$$.ptr;
            e.$$ = e.$$;
            let r = e.$$.ptrType.registeredClass,
              i = e.$$.ptr;
            for (; t.baseClass; ) (n = t.upcast(n)), (t = t.baseClass);
            for (; r.baseClass; ) (i = r.upcast(i)), (r = r.baseClass);
            return t === r && n === i;
          },
          clone() {
            if ((this.$$.ptr || Ve(this), this.$$.preservePointerOnDelete)) return (this.$$.count.value += 1), this;
            {
              let e = ge(Object.create(Object.getPrototypeOf(this), { $$: { value: Un(this.$$) } }));
              return (e.$$.count.value += 1), (e.$$.deleteScheduled = !1), e;
            }
          },
          delete() {
            this.$$.ptr || Ve(this),
              this.$$.deleteScheduled && !this.$$.preservePointerOnDelete && C('Object already scheduled for deletion'),
              Pt(this),
              At(this.$$),
              this.$$.preservePointerOnDelete || ((this.$$.smartPtr = void 0), (this.$$.ptr = void 0));
          },
          isDeleted() {
            return !this.$$.ptr;
          },
          deleteLater() {
            return (
              this.$$.ptr || Ve(this),
              this.$$.deleteScheduled && !this.$$.preservePointerOnDelete && C('Object already scheduled for deletion'),
              he.push(this),
              he.length === 1 && me && me(Ne),
              (this.$$.deleteScheduled = !0),
              this
            );
          },
        });
      };
      function ke() {}
      let ye = (e, t) => Object.defineProperty(t, 'name', { value: e }),
        Rt = (e, t, n) => {
          if (e[t].overloadTable === void 0) {
            let r = e[t];
            (e[t] = function (...i) {
              return (
                e[t].overloadTable.hasOwnProperty(i.length) ||
                  C(
                    `Function '${n}' called with an invalid number of arguments (${i.length}) - expects one of (${e[t].overloadTable})!`,
                  ),
                e[t].overloadTable[i.length].apply(this, i)
              );
            }),
              (e[t].overloadTable = []),
              (e[t].overloadTable[r.argCount] = r);
          }
        },
        qe = (e, t, n) => {
          a.hasOwnProperty(e)
            ? ((n === void 0 || (a[e].overloadTable !== void 0 && a[e].overloadTable[n] !== void 0)) &&
                C(`Cannot register public name '${e}' twice`),
              Rt(a, e, e),
              a.hasOwnProperty(n) &&
                C(`Cannot register multiple overloads of a function with the same number of arguments (${n})!`),
              (a[e].overloadTable[n] = t))
            : ((a[e] = t), n !== void 0 && (a[e].numArguments = n));
        },
        Xn = 48,
        Jn = 57,
        Kn = (e) => {
          if (e === void 0) return '_unknown';
          e = e.replace(/\W/g, '$');
          let t = e.charCodeAt(0);
          return t >= Xn && t <= Jn ? `_${e}` : e;
        };
      function Qn(e, t, n, r, i, s, l, c) {
        (this.name = e),
          (this.constructor = t),
          (this.instancePrototype = n),
          (this.rawDestructor = r),
          (this.baseClass = i),
          (this.getActualType = s),
          (this.upcast = l),
          (this.downcast = c),
          (this.pureVirtualFunctions = []);
      }
      let Ge = (e, t, n) => {
        for (; t !== n; )
          t.upcast || C(`Expected null or instance of ${n.name}, got an instance of ${t.name}`),
            (e = t.upcast(e)),
            (t = t.baseClass);
        return e;
      };
      function Zn(e, t) {
        if (t === null) return this.isReference && C(`null is not a valid ${this.name}`), 0;
        t.$$ || C(`Cannot pass "${et(t)}" as a ${this.name}`),
          t.$$.ptr || C(`Cannot pass deleted object as a pointer of type ${this.name}`);
        let n = t.$$.ptrType.registeredClass;
        return Ge(t.$$.ptr, n, this.registeredClass);
      }
      function er(e, t) {
        let n;
        if (t === null)
          return (
            this.isReference && C(`null is not a valid ${this.name}`),
            this.isSmartPointer ? ((n = this.rawConstructor()), e !== null && e.push(this.rawDestructor, n), n) : 0
          );
        (!t || !t.$$) && C(`Cannot pass "${et(t)}" as a ${this.name}`),
          t.$$.ptr || C(`Cannot pass deleted object as a pointer of type ${this.name}`),
          !this.isConst &&
            t.$$.ptrType.isConst &&
            C(
              `Cannot convert argument of type ${
                t.$$.smartPtrType ? t.$$.smartPtrType.name : t.$$.ptrType.name
              } to parameter type ${this.name}`,
            );
        let r = t.$$.ptrType.registeredClass;
        if (((n = Ge(t.$$.ptr, r, this.registeredClass)), this.isSmartPointer))
          switch (
            (t.$$.smartPtr === void 0 && C('Passing raw pointer to smart pointer is illegal'), this.sharingPolicy)
          ) {
            case 0:
              t.$$.smartPtrType === this
                ? (n = t.$$.smartPtr)
                : C(
                    `Cannot convert argument of type ${
                      t.$$.smartPtrType ? t.$$.smartPtrType.name : t.$$.ptrType.name
                    } to parameter type ${this.name}`,
                  );
              break;
            case 1:
              n = t.$$.smartPtr;
              break;
            case 2:
              if (t.$$.smartPtrType === this) n = t.$$.smartPtr;
              else {
                let i = t.clone();
                (n = this.rawShare(
                  n,
                  ee.toHandle(() => i.delete()),
                )),
                  e !== null && e.push(this.rawDestructor, n);
              }
              break;
            default:
              C('Unsupporting sharing policy');
          }
        return n;
      }
      function tr(e, t) {
        if (t === null) return this.isReference && C(`null is not a valid ${this.name}`), 0;
        t.$$ || C(`Cannot pass "${et(t)}" as a ${this.name}`),
          t.$$.ptr || C(`Cannot pass deleted object as a pointer of type ${this.name}`),
          t.$$.ptrType.isConst &&
            C(`Cannot convert argument of type ${t.$$.ptrType.name} to parameter type ${this.name}`);
        let n = t.$$.ptrType.registeredClass;
        return Ge(t.$$.ptr, n, this.registeredClass);
      }
      let nr = () => {
        Object.assign(ve.prototype, {
          getPointee(e) {
            return this.rawGetPointee && (e = this.rawGetPointee(e)), e;
          },
          destructor(e) {
            this.rawDestructor?.(e);
          },
          argPackAdvance: N,
          readValueFromPointer: pe,
          fromWireType: qn,
        });
      };
      function ve(e, t, n, r, i, s, l, c, u, f, p) {
        (this.name = e),
          (this.registeredClass = t),
          (this.isReference = n),
          (this.isConst = r),
          (this.isSmartPointer = i),
          (this.pointeeType = s),
          (this.sharingPolicy = l),
          (this.rawGetPointee = c),
          (this.rawConstructor = u),
          (this.rawShare = f),
          (this.rawDestructor = p),
          !i && t.baseClass === void 0
            ? r
              ? ((this.toWireType = Zn), (this.destructorFunction = null))
              : ((this.toWireType = tr), (this.destructorFunction = null))
            : (this.toWireType = er);
      }
      let Dt = (e, t, n) => {
          a.hasOwnProperty(e) || Pe('Replacing nonexistent public symbol'),
            a[e].overloadTable !== void 0 && n !== void 0
              ? (a[e].overloadTable[n] = t)
              : ((a[e] = t), (a[e].argCount = n));
        },
        rr = (e, t, n) => {
          e = e.replace(/p/g, 'i');
          let r = a[`dynCall_${e}`];
          return r(t, ...n);
        },
        xt,
        R = (e) => xt.get(e),
        ir = (e, t, n = []) => (e.includes('j') ? rr(e, t, n) : R(t)(...n)),
        or =
          (e, t) =>
          (...n) =>
            ir(e, t, n),
        U = (e, t) => {
          e = A(e);
          function n() {
            return e.includes('j') ? or(e, t) : R(t);
          }
          let r = n();
          return typeof r != 'function' && C(`unknown function pointer with signature ${e}: ${t}`), r;
        },
        sr = (e, t) => {
          let n = ye(t, function (r) {
            (this.name = t), (this.message = r);
            let i = new Error(r).stack;
            i !== void 0 &&
              (this.stack = `${this.toString()}
${i.replace(/^Error(:[^\n]*)?\n/, '')}`);
          });
          return (
            (n.prototype = Object.create(e.prototype)),
            (n.prototype.constructor = n),
            (n.prototype.toString = function () {
              return this.message === void 0 ? this.name : `${this.name}: ${this.message}`;
            }),
            n
          );
        },
        It,
        jt = (e) => {
          let t = Yt(e),
            n = A(t);
          return G(t), n;
        },
        Se = (e, t) => {
          let n = [],
            r = {};
          function i(s) {
            if (!r[s] && !Z[s]) {
              if (Le[s]) {
                Le[s].forEach(i);
                return;
              }
              n.push(s), (r[s] = !0);
            }
          }
          throw (t.forEach(i), new It(`${e}: ${n.map(jt).join([', '])}`));
        },
        ar = (e, t, n, r, i, s, l, c, u, f, p, w, y) => {
          (p = A(p)), (s = U(i, s)), c && (c = U(l, c)), f && (f = U(u, f)), (y = U(w, y));
          let F = Kn(p);
          qe(F, function () {
            Se(`Cannot construct ${p} due to unbound types`, [r]);
          }),
            X([e, t, n], r ? [r] : [], ($) => {
              var xe;
              $ = $[0];
              let O, x;
              r ? ((O = $.registeredClass), (x = O.instancePrototype)) : (x = ke.prototype);
              let B = ye(p, function (...it) {
                if (Object.getPrototypeOf(this) !== d) throw new le(`Use 'new' to construct ${p}`);
                if (h.constructor_body === void 0) throw new le(`${p} has no accessible constructor`);
                let Zt = h.constructor_body[it.length];
                if (Zt === void 0)
                  throw new le(
                    `Tried to invoke ctor of ${p} with invalid number of parameters (${
                      it.length
                    }) - expected (${Object.keys(h.constructor_body).toString()}) parameters instead!`,
                  );
                return Zt.apply(this, it);
              });
              var d = Object.create(x, { constructor: { value: B } });
              B.prototype = d;
              var h = new Qn(p, B, d, y, O, s, c, f);
              h.baseClass &&
                ((xe = h.baseClass).__derivedClasses ?? (xe.__derivedClasses = []),
                h.baseClass.__derivedClasses.push(h));
              let M = new ve(p, h, !0, !1, !1),
                I = new ve(`${p}*`, h, !1, !1, !1),
                te = new ve(`${p} const*`, h, !1, !0, !1);
              return (St[e] = { pointerType: I, constPointerType: te }), Dt(F, B), [M, I, te];
            });
        },
        Xe = (e, t) => {
          let n = [];
          for (let r = 0; r < e; r++) n.push(T[(t + r * 4) >> 2]);
          return n;
        };
      function cr(e) {
        for (let t = 1; t < e.length; ++t) if (e[t] !== null && e[t].destructorFunction === void 0) return !0;
        return !1;
      }
      function Je(e, t, n, r, i, s) {
        let l = t.length;
        l < 2 && C("argTypes array size mismatch! Must at least get return value and 'this' types!");
        let c = t[1] !== null && n !== null,
          u = cr(t),
          f = t[0].name !== 'void',
          p = l - 2,
          w = new Array(p),
          y = [],
          F = [];
        return ye(e, function (...O) {
          O.length !== p && C(`function ${e} called with ${O.length} arguments, expected ${p}`), (F.length = 0);
          let x;
          (y.length = c ? 2 : 1), (y[0] = i), c && ((x = t[1].toWireType(F, this)), (y[1] = x));
          for (let h = 0; h < p; ++h) (w[h] = t[h + 2].toWireType(F, O[h])), y.push(w[h]);
          let B = r(...y);
          function d(h) {
            if (u) ze(F);
            else
              for (let M = c ? 1 : 2; M < t.length; M++) {
                let I = M === 1 ? x : w[M - 2];
                t[M].destructorFunction !== null && t[M].destructorFunction(I);
              }
            if (f) return t[0].fromWireType(h);
          }
          return d(B);
        });
      }
      let lr = (e, t, n, r, i, s) => {
          let l = Xe(t, n);
          (i = U(r, i)),
            X([], [e], (c) => {
              c = c[0];
              let u = `constructor ${c.name}`;
              if (
                (c.registeredClass.constructor_body === void 0 && (c.registeredClass.constructor_body = []),
                c.registeredClass.constructor_body[t - 1] !== void 0)
              )
                throw new le(
                  `Cannot register multiple constructors with identical number of parameters (${t - 1}) for class '${
                    c.name
                  }'! Overload resolution is currently only performed using the parameter count, not actual type info!`,
                );
              return (
                (c.registeredClass.constructor_body[t - 1] = () => {
                  Se(`Cannot construct ${c.name} due to unbound types`, l);
                }),
                X(
                  [],
                  l,
                  (f) => (f.splice(1, 0, null), (c.registeredClass.constructor_body[t - 1] = Je(u, f, null, i, s)), []),
                ),
                []
              );
            });
        },
        Wt = (e) => {
          e = e.trim();
          let t = e.indexOf('(');
          return t !== -1 ? e.substr(0, t) : e;
        },
        ur = (e, t, n, r, i, s, l, c, u) => {
          let f = Xe(n, r);
          (t = A(t)),
            (t = Wt(t)),
            (s = U(i, s)),
            X([], [e], (p) => {
              p = p[0];
              let w = `${p.name}.${t}`;
              t.startsWith('@@') && (t = Symbol[t.substring(2)]), c && p.registeredClass.pureVirtualFunctions.push(t);
              function y() {
                Se(`Cannot call ${w} due to unbound types`, f);
              }
              let F = p.registeredClass.instancePrototype,
                $ = F[t];
              return (
                $ === void 0 || ($.overloadTable === void 0 && $.className !== p.name && $.argCount === n - 2)
                  ? ((y.argCount = n - 2), (y.className = p.name), (F[t] = y))
                  : (Rt(F, t, w), (F[t].overloadTable[n - 2] = y)),
                X([], f, (O) => {
                  let x = Je(w, O, p, s, l);
                  return (
                    F[t].overloadTable === void 0
                      ? ((x.argCount = n - 2), (F[t] = x))
                      : (F[t].overloadTable[n - 2] = x),
                    []
                  );
                }),
                []
              );
            });
        },
        Ke = [],
        q = [],
        Qe = (e) => {
          e > 9 && --q[e + 1] === 0 && ((q[e] = void 0), Ke.push(e));
        },
        dr = () => q.length / 2 - 5 - Ke.length,
        fr = () => {
          q.push(0, 1, void 0, 1, null, 1, !0, 1, !1, 1), (a.count_emval_handles = dr);
        };
      var ee = {
        toValue: (e) => (e || C(`Cannot use deleted val. handle = ${e}`), q[e]),
        toHandle: (e) => {
          switch (e) {
            case void 0:
              return 2;
            case null:
              return 4;
            case !0:
              return 6;
            case !1:
              return 8;
            default: {
              let t = Ke.pop() || q.length;
              return (q[t] = e), (q[t + 1] = 1), t;
            }
          }
        },
      };
      let pr = {
          name: 'emscripten::val',
          fromWireType: (e) => {
            let t = ee.toValue(e);
            return Qe(e), t;
          },
          toWireType: (e, t) => ee.toHandle(t),
          argPackAdvance: N,
          readValueFromPointer: pe,
          destructorFunction: null,
        },
        Ut = (e) => Y(e, pr),
        hr = (e, t, n) => {
          switch (t) {
            case 1:
              return n
                ? function (r) {
                    return this.fromWireType(H[r]);
                  }
                : function (r) {
                    return this.fromWireType(P[r]);
                  };
            case 2:
              return n
                ? function (r) {
                    return this.fromWireType(oe[r >> 1]);
                  }
                : function (r) {
                    return this.fromWireType(de[r >> 1]);
                  };
            case 4:
              return n
                ? function (r) {
                    return this.fromWireType(S[r >> 2]);
                  }
                : function (r) {
                    return this.fromWireType(T[r >> 2]);
                  };
            default:
              throw new TypeError(`invalid integer width (${t}): ${e}`);
          }
        },
        mr = (e, t, n, r) => {
          t = A(t);
          function i() {}
          (i.values = {}),
            Y(e, {
              name: t,
              constructor: i,
              fromWireType(s) {
                return this.constructor.values[s];
              },
              toWireType: (s, l) => l.value,
              argPackAdvance: N,
              readValueFromPointer: hr(t, n, r),
              destructorFunction: null,
            }),
            qe(t, i);
        },
        Ze = (e, t) => {
          let n = Z[e];
          return n === void 0 && C(`${t} has unknown type ${jt(e)}`), n;
        },
        _r = (e, t, n) => {
          let r = Ze(e, 'enum');
          t = A(t);
          let i = r.constructor,
            s = Object.create(r.constructor.prototype, {
              value: { value: n },
              constructor: { value: ye(`${r.name}_${t}`, function () {}) },
            });
          (i.values[n] = s), (i[t] = s);
        };
      var et = (e) => {
        if (e === null) return 'null';
        let t = typeof e;
        return t === 'object' || t === 'array' || t === 'function' ? e.toString() : `${e}`;
      };
      let gr = (e, t) => {
          switch (t) {
            case 4:
              return function (n) {
                return this.fromWireType(pt[n >> 2]);
              };
            case 8:
              return function (n) {
                return this.fromWireType(ht[n >> 3]);
              };
            default:
              throw new TypeError(`invalid float width (${t}): ${e}`);
          }
        },
        yr = (e, t, n) => {
          (t = A(t)),
            Y(e, {
              name: t,
              fromWireType: (r) => r,
              toWireType: (r, i) => i,
              argPackAdvance: N,
              readValueFromPointer: gr(t, n),
              destructorFunction: null,
            });
        },
        vr = (e, t, n, r, i, s, l) => {
          let c = Xe(t, n);
          (e = A(e)),
            (e = Wt(e)),
            (i = U(r, i)),
            qe(
              e,
              function () {
                Se(`Cannot call ${e} due to unbound types`, c);
              },
              t - 1,
            ),
            X([], c, (u) => {
              let f = [u[0], null].concat(u.slice(1));
              return Dt(e, Je(e, f, null, i, s), t - 1), [];
            });
        },
        br = (e, t, n) => {
          switch (t) {
            case 1:
              return n ? (r) => H[r] : (r) => P[r];
            case 2:
              return n ? (r) => oe[r >> 1] : (r) => de[r >> 1];
            case 4:
              return n ? (r) => S[r >> 2] : (r) => T[r >> 2];
            default:
              throw new TypeError(`invalid integer width (${t}): ${e}`);
          }
        },
        Cr = (e, t, n, r, i) => {
          t = A(t);
          let s = (f) => f;
          if (r === 0) {
            let f = 32 - 8 * n;
            s = (p) => (p << f) >>> f;
          }
          let l = t.includes('unsigned'),
            c = (f, p) => {},
            u;
          l
            ? (u = function (f, p) {
                return c(p, this.name), p >>> 0;
              })
            : (u = function (f, p) {
                return c(p, this.name), p;
              }),
            Y(e, {
              name: t,
              fromWireType: s,
              toWireType: u,
              argPackAdvance: N,
              readValueFromPointer: br(t, n, r !== 0),
              destructorFunction: null,
            });
        },
        wr = (e, t, n) => {
          let i = [Int8Array, Uint8Array, Int16Array, Uint16Array, Int32Array, Uint32Array, Float32Array, Float64Array][
            t
          ];
          function s(l) {
            let c = T[l >> 2],
              u = T[(l + 4) >> 2];
            return new i(H.buffer, u, c);
          }
          (n = A(n)),
            Y(
              e,
              { name: n, fromWireType: s, argPackAdvance: N, readValueFromPointer: s },
              { ignoreDuplicateRegistrations: !0 },
            );
        },
        Er = (e, t) => {
          Ut(e);
        },
        Tr = (e, t, n, r, i, s, l, c, u, f, p, w) => {
          (n = A(n)),
            (s = U(i, s)),
            (c = U(l, c)),
            (f = U(u, f)),
            (w = U(p, w)),
            X([e], [t], (y) => ((y = y[0]), [new ve(n, y.registeredClass, !1, !1, !0, y, r, s, c, f, w)]));
        },
        Fr = (e, t) => {
          t = A(t);
          let n = t === 'std::string';
          Y(e, {
            name: t,
            fromWireType(r) {
              let i = T[r >> 2],
                s = r + 4,
                l;
              if (n) {
                let u = s;
                for (var c = 0; c <= i; ++c) {
                  let f = s + c;
                  if (c == i || P[f] == 0) {
                    let p = f - u,
                      w = Q(u, p);
                    l === void 0 ? (l = w) : ((l += '\0'), (l += w)), (u = f + 1);
                  }
                }
              } else {
                let u = new Array(i);
                for (var c = 0; c < i; ++c) u[c] = String.fromCharCode(P[s + c]);
                l = u.join('');
              }
              return G(r), l;
            },
            toWireType(r, i) {
              i instanceof ArrayBuffer && (i = new Uint8Array(i));
              let s,
                l = typeof i == 'string';
              l ||
                i instanceof Uint8Array ||
                i instanceof Uint8ClampedArray ||
                i instanceof Int8Array ||
                C('Cannot pass non-string to std::string'),
                n && l ? (s = Ft(i)) : (s = i.length);
              let c = rt(4 + s + 1),
                u = c + 4;
              if (((T[c >> 2] = s), n && l)) Ln(i, u, s + 1);
              else if (l)
                for (var f = 0; f < s; ++f) {
                  let p = i.charCodeAt(f);
                  p > 255 && (G(u), C('String has UTF-16 code units that do not fit in 8 bits')), (P[u + f] = p);
                }
              else for (var f = 0; f < s; ++f) P[u + f] = i[f];
              return r !== null && r.push(G, c), c;
            },
            argPackAdvance: N,
            readValueFromPointer: pe,
            destructorFunction(r) {
              G(r);
            },
          });
        },
        Ot = typeof TextDecoder < 'u' ? new TextDecoder('utf-16le') : void 0,
        Mr = (e, t) => {
          let n = e,
            r = n >> 1,
            i = r + t / 2;
          for (; !(r >= i) && de[r]; ) ++r;
          if (((n = r << 1), n - e > 32 && Ot)) return Ot.decode(P.subarray(e, n));
          let s = '';
          for (let l = 0; !(l >= t / 2); ++l) {
            let c = oe[(e + l * 2) >> 1];
            if (c == 0) break;
            s += String.fromCharCode(c);
          }
          return s;
        },
        $r = (e, t, n) => {
          if ((n ?? (n = 2147483647), n < 2)) return 0;
          n -= 2;
          let r = t,
            i = n < e.length * 2 ? n / 2 : e.length;
          for (let s = 0; s < i; ++s) {
            let l = e.charCodeAt(s);
            (oe[t >> 1] = l), (t += 2);
          }
          return (oe[t >> 1] = 0), t - r;
        },
        Lr = (e) => e.length * 2,
        Pr = (e, t) => {
          let n = 0,
            r = '';
          for (; !(n >= t / 4); ) {
            let i = S[(e + n * 4) >> 2];
            if (i == 0) break;
            if ((++n, i >= 65536)) {
              let s = i - 65536;
              r += String.fromCharCode(55296 | (s >> 10), 56320 | (s & 1023));
            } else r += String.fromCharCode(i);
          }
          return r;
        },
        Ar = (e, t, n) => {
          if ((n ?? (n = 2147483647), n < 4)) return 0;
          let r = t,
            i = r + n - 4;
          for (let s = 0; s < e.length; ++s) {
            let l = e.charCodeAt(s);
            if (l >= 55296 && l <= 57343) {
              let c = e.charCodeAt(++s);
              l = (65536 + ((l & 1023) << 10)) | (c & 1023);
            }
            if (((S[t >> 2] = l), (t += 4), t + 4 > i)) break;
          }
          return (S[t >> 2] = 0), t - r;
        },
        kr = (e) => {
          let t = 0;
          for (let n = 0; n < e.length; ++n) {
            let r = e.charCodeAt(n);
            r >= 55296 && r <= 57343 && ++n, (t += 4);
          }
          return t;
        },
        Sr = (e, t, n) => {
          n = A(n);
          let r, i, s, l;
          t === 2
            ? ((r = Mr), (i = $r), (l = Lr), (s = (c) => de[c >> 1]))
            : t === 4 && ((r = Pr), (i = Ar), (l = kr), (s = (c) => T[c >> 2])),
            Y(e, {
              name: n,
              fromWireType: (c) => {
                let u = T[c >> 2],
                  f,
                  p = c + 4;
                for (let w = 0; w <= u; ++w) {
                  let y = c + 4 + w * t;
                  if (w == u || s(y) == 0) {
                    let F = y - p,
                      $ = r(p, F);
                    f === void 0 ? (f = $) : ((f += '\0'), (f += $)), (p = y + t);
                  }
                }
                return G(c), f;
              },
              toWireType: (c, u) => {
                typeof u != 'string' && C(`Cannot pass non-string to C++ string type ${n}`);
                let f = l(u),
                  p = rt(4 + f + t);
                return (T[p >> 2] = f / t), i(u, p + 4, f + t), c !== null && c.push(G, p), p;
              },
              argPackAdvance: N,
              readValueFromPointer: pe,
              destructorFunction(c) {
                G(c);
              },
            });
        },
        Rr = (e, t, n, r, i, s) => {
          $e[e] = { name: A(t), rawConstructor: U(n, r), rawDestructor: U(i, s), fields: [] };
        },
        Dr = (e, t, n, r, i, s, l, c, u, f) => {
          $e[e].fields.push({
            fieldName: A(t),
            getterReturnType: n,
            getter: U(r, i),
            getterContext: s,
            setterArgumentType: l,
            setter: U(c, u),
            setterContext: f,
          });
        },
        xr = (e, t) => {
          (t = A(t)),
            Y(e, { isVoid: !0, name: t, argPackAdvance: 0, fromWireType: () => {}, toWireType: (n, r) => {} });
        },
        Ir = (e, t, n) => P.copyWithin(e, t, t + n),
        jr = () => {
          throw 1 / 0;
        },
        tt = [],
        Wr = (e, t, n, r) => ((e = tt[e]), (t = ee.toValue(t)), e(null, t, n, r)),
        Ur = (e) => {
          let t = tt.length;
          return tt.push(e), t;
        },
        Or = (e, t) => {
          let n = new Array(e);
          for (let r = 0; r < e; ++r) n[r] = Ze(T[(t + r * 4) >> 2], `parameter ${r}`);
          return n;
        },
        Br = Reflect.construct,
        Hr = (e, t, n) => {
          let r = [],
            i = e.toWireType(r, n);
          return r.length && (T[t >> 2] = ee.toHandle(r)), i;
        },
        zr = (e, t, n) => {
          let r = Or(e, t),
            i = r.shift();
          e--;
          let s = new Array(e),
            l = (u, f, p, w) => {
              let y = 0;
              for (let $ = 0; $ < e; ++$) (s[$] = r[$].readValueFromPointer(w + y)), (y += r[$].argPackAdvance);
              let F = n === 1 ? Br(f, s) : f.apply(u, s);
              return Hr(i, p, F);
            },
            c = `methodCaller<(${r.map((u) => u.name).join(', ')}) => ${i.name}>`;
          return Ur(ye(c, l));
        },
        Vr = (e) => {
          e > 9 && (q[e + 1] += 1);
        },
        Yr = (e) => {
          let t = ee.toValue(e);
          ze(t), Qe(e);
        },
        Nr = (e, t) => {
          e = Ze(e, '_emval_take_value');
          let n = e.readValueFromPointer(t);
          return ee.toHandle(n);
        },
        qr = () => {
          Fe('');
        },
        Bt;
      Bt = () => performance.now();
      let Gr = () => 2147483648,
        Xr = (e) => {
          let t = Te.buffer,
            n = (e - t.byteLength + 65535) / 65536;
          try {
            return Te.grow(n), mt(), 1;
          } catch {}
        },
        Jr = (e) => {
          let t = P.length;
          e >>>= 0;
          let n = Gr();
          if (e > n) return !1;
          let r = (i, s) => i + ((s - (i % s)) % s);
          for (let i = 1; i <= 4; i *= 2) {
            let s = t * (1 + 0.2 / i);
            s = Math.min(s, e + 100663296);
            let l = Math.min(n, r(Math.max(e, s), 65536));
            if (Xr(l)) return !0;
          }
          return !1;
        },
        nt = {},
        Kr = () => J || './this.program';
      var be = () => {
        if (!be.strings) {
          let n = {
            USER: 'web_user',
            LOGNAME: 'web_user',
            PATH: '/',
            PWD: '/',
            HOME: '/home/web_user',
            LANG: `${((typeof navigator == 'object' && navigator.languages && navigator.languages[0]) || 'C').replace(
              '-',
              '_',
            )}.UTF-8`,
            _: Kr(),
          };
          for (var e in nt) nt[e] === void 0 ? delete n[e] : (n[e] = nt[e]);
          let r = [];
          for (var e in n) r.push(`${e}=${n[e]}`);
          be.strings = r;
        }
        return be.strings;
      };
      let Qr = (e, t) => {
          for (let n = 0; n < e.length; ++n) H[t++] = e.charCodeAt(n);
          H[t] = 0;
        },
        Zr = (e, t) => {
          let n = 0;
          return (
            be().forEach((r, i) => {
              let s = t + n;
              (T[(e + i * 4) >> 2] = s), Qr(r, s), (n += r.length + 1);
            }),
            0
          );
        },
        ei = (e, t) => {
          let n = be();
          T[e >> 2] = n.length;
          let r = 0;
          return n.forEach((i) => (r += i.length + 1)), (T[t >> 2] = r), 0;
        },
        ti = (e) => 52,
        ni = (e, t, n, r) => 52;
      function ii(e, t, n, r, i) {
        return 70;
      }
      let oi = [null, [], []],
        si = (e, t) => {
          let n = oi[e];
          t === 0 || t === 10 ? ((e === 1 ? on : ie)(Et(n, 0)), (n.length = 0)) : n.push(t);
        },
        ai = (e, t, n, r) => {
          let i = 0;
          for (let s = 0; s < n; s++) {
            let l = T[t >> 2],
              c = T[(t + 4) >> 2];
            t += 8;
            for (let u = 0; u < c; u++) si(e, P[l + u]);
            i += c;
          }
          return (T[r >> 2] = i), 0;
        },
        ci = () => {
          if (typeof crypto == 'object' && typeof crypto.getRandomValues == 'function')
            return (e) => crypto.getRandomValues(e);
          Fe('initRandomDevice');
        };
      var Ht = (e) => (Ht = ci())(e);
      let li = (e, t) => (Ht(P.subarray(e, e + t)), 0),
        Re = (e) => e % 4 === 0 && (e % 100 !== 0 || e % 400 === 0),
        ui = (e, t) => {
          let n = 0;
          for (let r = 0; r <= t; n += e[r++]);
          return n;
        },
        zt = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31],
        Vt = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31],
        di = (e, t) => {
          let n = new Date(e.getTime());
          for (; t > 0; ) {
            let r = Re(n.getFullYear()),
              i = n.getMonth(),
              s = (r ? zt : Vt)[i];
            if (t > s - n.getDate())
              (t -= s - n.getDate() + 1),
                n.setDate(1),
                i < 11 ? n.setMonth(i + 1) : (n.setMonth(0), n.setFullYear(n.getFullYear() + 1));
            else return n.setDate(n.getDate() + t), n;
          }
          return n;
        };
      function fi(e, t, n) {
        let r = n > 0 ? n : Ft(e) + 1,
          i = new Array(r),
          s = Mt(e, i, 0, i.length);
        return t && (i.length = s), i;
      }
      let pi = (e, t) => {
          H.set(e, t);
        },
        hi = (e, t, n, r) => {
          let i = T[(r + 40) >> 2],
            s = {
              tm_sec: S[r >> 2],
              tm_min: S[(r + 4) >> 2],
              tm_hour: S[(r + 8) >> 2],
              tm_mday: S[(r + 12) >> 2],
              tm_mon: S[(r + 16) >> 2],
              tm_year: S[(r + 20) >> 2],
              tm_wday: S[(r + 24) >> 2],
              tm_yday: S[(r + 28) >> 2],
              tm_isdst: S[(r + 32) >> 2],
              tm_gmtoff: S[(r + 36) >> 2],
              tm_zone: i ? Q(i) : '',
            },
            l = Q(n),
            c = {
              '%c': '%a %b %d %H:%M:%S %Y',
              '%D': '%m/%d/%y',
              '%F': '%Y-%m-%d',
              '%h': '%b',
              '%r': '%I:%M:%S %p',
              '%R': '%H:%M',
              '%T': '%H:%M:%S',
              '%x': '%m/%d/%y',
              '%X': '%H:%M:%S',
              '%Ec': '%c',
              '%EC': '%C',
              '%Ex': '%m/%d/%y',
              '%EX': '%H:%M:%S',
              '%Ey': '%y',
              '%EY': '%Y',
              '%Od': '%d',
              '%Oe': '%e',
              '%OH': '%H',
              '%OI': '%I',
              '%Om': '%m',
              '%OM': '%M',
              '%OS': '%S',
              '%Ou': '%u',
              '%OU': '%U',
              '%OV': '%V',
              '%Ow': '%w',
              '%OW': '%W',
              '%Oy': '%y',
            };
          for (var u in c) l = l.replace(new RegExp(u, 'g'), c[u]);
          let f = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
            p = [
              'January',
              'February',
              'March',
              'April',
              'May',
              'June',
              'July',
              'August',
              'September',
              'October',
              'November',
              'December',
            ];
          function w(d, h, M) {
            let I = typeof d == 'number' ? d.toString() : d || '';
            for (; I.length < h; ) I = M[0] + I;
            return I;
          }
          function y(d, h) {
            return w(d, h, '0');
          }
          function F(d, h) {
            function M(te) {
              return te < 0 ? -1 : te > 0 ? 1 : 0;
            }
            let I;
            return (
              (I = M(d.getFullYear() - h.getFullYear())) === 0 &&
                (I = M(d.getMonth() - h.getMonth())) === 0 &&
                (I = M(d.getDate() - h.getDate())),
              I
            );
          }
          function $(d) {
            switch (d.getDay()) {
              case 0:
                return new Date(d.getFullYear() - 1, 11, 29);
              case 1:
                return d;
              case 2:
                return new Date(d.getFullYear(), 0, 3);
              case 3:
                return new Date(d.getFullYear(), 0, 2);
              case 4:
                return new Date(d.getFullYear(), 0, 1);
              case 5:
                return new Date(d.getFullYear() - 1, 11, 31);
              case 6:
                return new Date(d.getFullYear() - 1, 11, 30);
            }
          }
          function O(d) {
            let h = di(new Date(d.tm_year + 1900, 0, 1), d.tm_yday),
              M = new Date(h.getFullYear(), 0, 4),
              I = new Date(h.getFullYear() + 1, 0, 4),
              te = $(M),
              xe = $(I);
            return F(te, h) <= 0 ? (F(xe, h) <= 0 ? h.getFullYear() + 1 : h.getFullYear()) : h.getFullYear() - 1;
          }
          let x = {
            '%a': (d) => f[d.tm_wday].substring(0, 3),
            '%A': (d) => f[d.tm_wday],
            '%b': (d) => p[d.tm_mon].substring(0, 3),
            '%B': (d) => p[d.tm_mon],
            '%C': (d) => {
              let h = d.tm_year + 1900;
              return y((h / 100) | 0, 2);
            },
            '%d': (d) => y(d.tm_mday, 2),
            '%e': (d) => w(d.tm_mday, 2, ' '),
            '%g': (d) => O(d).toString().substring(2),
            '%G': O,
            '%H': (d) => y(d.tm_hour, 2),
            '%I': (d) => {
              let h = d.tm_hour;
              return h == 0 ? (h = 12) : h > 12 && (h -= 12), y(h, 2);
            },
            '%j': (d) => y(d.tm_mday + ui(Re(d.tm_year + 1900) ? zt : Vt, d.tm_mon - 1), 3),
            '%m': (d) => y(d.tm_mon + 1, 2),
            '%M': (d) => y(d.tm_min, 2),
            '%n': () => `
`,
            '%p': (d) => (d.tm_hour >= 0 && d.tm_hour < 12 ? 'AM' : 'PM'),
            '%S': (d) => y(d.tm_sec, 2),
            '%t': () => '	',
            '%u': (d) => d.tm_wday || 7,
            '%U': (d) => {
              let h = d.tm_yday + 7 - d.tm_wday;
              return y(Math.floor(h / 7), 2);
            },
            '%V': (d) => {
              let h = Math.floor((d.tm_yday + 7 - ((d.tm_wday + 6) % 7)) / 7);
              if (((d.tm_wday + 371 - d.tm_yday - 2) % 7 <= 2 && h++, h)) {
                if (h == 53) {
                  let M = (d.tm_wday + 371 - d.tm_yday) % 7;
                  M != 4 && (M != 3 || !Re(d.tm_year)) && (h = 1);
                }
              } else {
                h = 52;
                let M = (d.tm_wday + 7 - d.tm_yday - 1) % 7;
                (M == 4 || (M == 5 && Re((d.tm_year % 400) - 1))) && h++;
              }
              return y(h, 2);
            },
            '%w': (d) => d.tm_wday,
            '%W': (d) => {
              let h = d.tm_yday + 7 - ((d.tm_wday + 6) % 7);
              return y(Math.floor(h / 7), 2);
            },
            '%y': (d) => (d.tm_year + 1900).toString().substring(2),
            '%Y': (d) => d.tm_year + 1900,
            '%z': (d) => {
              let h = d.tm_gmtoff,
                M = h >= 0;
              return (h = Math.abs(h) / 60), (h = (h / 60) * 100 + (h % 60)), (M ? '+' : '-') + `0000${h}`.slice(-4);
            },
            '%Z': (d) => d.tm_zone,
            '%%': () => '%',
          };
          l = l.replace(/%%/g, '\0\0');
          for (var u in x) l.includes(u) && (l = l.replace(new RegExp(u, 'g'), x[u](s)));
          l = l.replace(/\0\0/g, '%');
          let B = fi(l, !1);
          return B.length > t ? 0 : (pi(B, e), B.length - 1);
        },
        mi = (e, t, n, r, i) => hi(e, t, n, r);
      ($t = a.InternalError =
        class extends Error {
          constructor(t) {
            super(t), (this.name = 'InternalError');
          }
        }),
        In(),
        (le = a.BindingError =
          class extends Error {
            constructor(t) {
              super(t), (this.name = 'BindingError');
            }
          }),
        Gn(),
        Vn(),
        nr(),
        (It = a.UnboundTypeError = sr(Error, 'UnboundTypeError')),
        fr();
      var _i = {
          c: bn,
          d: En,
          q: Fn,
          h: Cn,
          E: Mn,
          W: $n,
          T: Pn,
          X: An,
          U: kn,
          D: Sn,
          V: Rn,
          A: Dn,
          O: xn,
          ea: Wn,
          z: ar,
          x: lr,
          i: ur,
          da: Ut,
          B: mr,
          n: _r,
          I: yr,
          K: vr,
          p: Cr,
          k: wr,
          L: Er,
          ka: Tr,
          J: Fr,
          y: Sr,
          u: Rr,
          m: Dr,
          fa: xr,
          Y: Ir,
          P: jr,
          ia: Wr,
          R: Qe,
          ha: zr,
          ja: Vr,
          ga: Yr,
          t: Nr,
          ca: qr,
          l: Bt,
          S: Jr,
          Z: Zr,
          _: ei,
          w: ti,
          C: ni,
          N: ii,
          v: ai,
          $: li,
          F: Vi,
          j: ji,
          g: Ii,
          e: zi,
          ba: Ri,
          s: Hi,
          G: Oi,
          r: Ui,
          b: Si,
          a: Di,
          f: xi,
          o: Bi,
          H: Wi,
          aa: Yi,
          M: Ni,
          Q: mi,
        },
        E = vn(),
        rt = (e) => (rt = E.na)(e),
        Yt = (e) => (Yt = E.oa)(e),
        G = (e) => (G = E.qa)(e),
        D = (e, t) => (D = E.ra)(e, t),
        Nt = (e) => (Nt = E.sa)(e),
        qt = (e) => (qt = E.ta)(e),
        Gt = () => (Gt = E.ua)(),
        Xt = (e, t, n) => (Xt = E.va)(e, t, n),
        Jt = (e) => (Jt = E.wa)(e);
      a.dynCall_iijj = (e, t, n, r, i, s) => (a.dynCall_iijj = E.xa)(e, t, n, r, i, s);
      a.dynCall_vijj = (e, t, n, r, i, s) => (a.dynCall_vijj = E.ya)(e, t, n, r, i, s);
      a.dynCall_jiii = (e, t, n, r) => (a.dynCall_jiii = E.za)(e, t, n, r);
      a.dynCall_jii = (e, t, n) => (a.dynCall_jii = E.Aa)(e, t, n);
      var Kt = (a.dynCall_viiij = (e, t, n, r, i, s) => (Kt = a.dynCall_viiij = E.Ba)(e, t, n, r, i, s));
      a.dynCall_jiji = (e, t, n, r, i) => (a.dynCall_jiji = E.Ca)(e, t, n, r, i);
      a.dynCall_viijii = (e, t, n, r, i, s, l) => (a.dynCall_viijii = E.Da)(e, t, n, r, i, s, l);
      a.dynCall_iiiiij = (e, t, n, r, i, s, l) => (a.dynCall_iiiiij = E.Ea)(e, t, n, r, i, s, l);
      a.dynCall_iiiiijj = (e, t, n, r, i, s, l, c, u) => (a.dynCall_iiiiijj = E.Fa)(e, t, n, r, i, s, l, c, u);
      a.dynCall_iiiiiijj = (e, t, n, r, i, s, l, c, u, f) => (a.dynCall_iiiiiijj = E.Ga)(e, t, n, r, i, s, l, c, u, f);
      function Si(e, t) {
        let n = W();
        try {
          R(e)(t);
        } catch (r) {
          if ((j(n), r !== r + 0)) throw r;
          D(1, 0);
        }
      }
      function Ri(e, t, n, r, i) {
        let s = W();
        try {
          return R(e)(t, n, r, i);
        } catch (l) {
          if ((j(s), l !== l + 0)) throw l;
          D(1, 0);
        }
      }
      function Di(e, t, n) {
        let r = W();
        try {
          R(e)(t, n);
        } catch (i) {
          if ((j(r), i !== i + 0)) throw i;
          D(1, 0);
        }
      }
      function xi(e, t, n, r) {
        let i = W();
        try {
          R(e)(t, n, r);
        } catch (s) {
          if ((j(i), s !== s + 0)) throw s;
          D(1, 0);
        }
      }
      function Ii(e, t, n) {
        let r = W();
        try {
          return R(e)(t, n);
        } catch (i) {
          if ((j(r), i !== i + 0)) throw i;
          D(1, 0);
        }
      }
      function ji(e, t) {
        let n = W();
        try {
          return R(e)(t);
        } catch (r) {
          if ((j(n), r !== r + 0)) throw r;
          D(1, 0);
        }
      }
      function Wi(e, t, n, r, i, s) {
        let l = W();
        try {
          R(e)(t, n, r, i, s);
        } catch (c) {
          if ((j(l), c !== c + 0)) throw c;
          D(1, 0);
        }
      }
      function Ui(e) {
        let t = W();
        try {
          R(e)();
        } catch (n) {
          if ((j(t), n !== n + 0)) throw n;
          D(1, 0);
        }
      }
      function Oi(e, t, n, r, i, s, l, c) {
        let u = W();
        try {
          return R(e)(t, n, r, i, s, l, c);
        } catch (f) {
          if ((j(u), f !== f + 0)) throw f;
          D(1, 0);
        }
      }
      function Bi(e, t, n, r, i) {
        let s = W();
        try {
          R(e)(t, n, r, i);
        } catch (l) {
          if ((j(s), l !== l + 0)) throw l;
          D(1, 0);
        }
      }
      function Hi(e, t, n, r, i, s) {
        let l = W();
        try {
          return R(e)(t, n, r, i, s);
        } catch (c) {
          if ((j(l), c !== c + 0)) throw c;
          D(1, 0);
        }
      }
      function zi(e, t, n, r) {
        let i = W();
        try {
          return R(e)(t, n, r);
        } catch (s) {
          if ((j(i), s !== s + 0)) throw s;
          D(1, 0);
        }
      }
      function Vi(e) {
        let t = W();
        try {
          return R(e)();
        } catch (n) {
          if ((j(t), n !== n + 0)) throw n;
          D(1, 0);
        }
      }
      function Yi(e, t, n, r, i, s, l) {
        let c = W();
        try {
          R(e)(t, n, r, i, s, l);
        } catch (u) {
          if ((j(c), u !== u + 0)) throw u;
          D(1, 0);
        }
      }
      function Ni(e, t, n, r, i, s) {
        let l = W();
        try {
          Kt(e, t, n, r, i, s);
        } catch (c) {
          if ((j(l), c !== c + 0)) throw c;
          D(1, 0);
        }
      }
      let De;
      fe = function e() {
        De || Qt(), De || (fe = e);
      };
      function Qt() {
        if (K > 0 || (cn(), K > 0)) return;
        function e() {
          De ||
            ((De = !0),
            (a.calledRun = !0),
            !ft && (ln(), _(a), a.onRuntimeInitialized && a.onRuntimeInitialized(), un()));
        }
        a.setStatus
          ? (a.setStatus('Running...'),
            setTimeout(function () {
              setTimeout(function () {
                a.setStatus('');
              }, 1),
                e();
            }, 1))
          : e();
      }
      if (a.preInit)
        for (typeof a.preInit == 'function' && (a.preInit = [a.preInit]); a.preInit.length > 0; ) a.preInit.pop()();
      return Qt(), k;
    };
  })(),
  en = Ji;
var ne = class {
  constructor() {
    throw new Error('RendererLoader is a static class and cannot be instantiated.');
  }
  static async _tryLoad(o) {
    return await en({ locateFile: () => o });
  }
  static async _loadWithBackup() {
    return (
      this._ModulePromise ||
        (this._ModulePromise = this._tryLoad(this._wasmURL).catch(async (o) => {
          let a = `https://unpkg.com/${Ce.name}@${Ce.version}/dist/dotlottie-player.wasm`;
          console.warn(`Primary WASM load failed from ${this._wasmURL}. Error: ${o.message}`),
            console.warn(`Attempting to load WASM from backup URL: ${a}`);
          try {
            return await this._tryLoad(a);
          } catch (_) {
            throw (
              (console.error(`Primary WASM URL failed: ${o.message}`),
              console.error(`Backup WASM URL failed: ${_.message}`),
              new Error('WASM loading failed from all sources.'))
            );
          }
        })),
      this._ModulePromise
    );
  }
  static async load() {
    return this._loadWithBackup();
  }
  static setWasmUrl(o) {
    (this._wasmURL = o), (this._ModulePromise = null);
  }
};
L(ne, '_ModulePromise', null),
  L(ne, '_wasmURL', `https://cdn.jsdelivr.net/npm/${Ce.name}@${Ce.version}/dist/dotlottie-player.wasm`);
var je = class {
  constructor() {
    L(this, '_eventListeners', new Map());
  }
  addEventListener(o, a) {
    let _ = this._eventListeners.get(o);
    _ || ((_ = new Set()), this._eventListeners.set(o, _)), _.add(a);
  }
  removeEventListener(o, a) {
    let _ = this._eventListeners.get(o);
    _ && (a ? (_.delete(a), _.size === 0 && this._eventListeners.delete(o)) : this._eventListeners.delete(o));
  }
  dispatch(o) {
    this._eventListeners.get(o.type)?.forEach((_) => _(o));
  }
  removeAllEventListeners() {
    this._eventListeners.clear();
  }
};
var ct = (v, o) =>
    v === 'reverse'
      ? o.Mode.Reverse
      : v === 'bounce'
      ? o.Mode.Bounce
      : v === 'reverse-bounce'
      ? o.Mode.ReverseBounce
      : o.Mode.Forward,
  lt = (v, o) =>
    v === 'contain'
      ? o.Fit.Contain
      : v === 'cover'
      ? o.Fit.Cover
      : v === 'fill'
      ? o.Fit.Fill
      : v === 'fit-height'
      ? o.Fit.FitHeight
      : v === 'fit-width'
      ? o.Fit.FitWidth
      : o.Fit.None,
  ut = (v, o) => {
    let a = new o.VectorFloat();
    return a.push_back(v[0]), a.push_back(v[1]), a;
  },
  dt = (v, o) => {
    let a = new o.VectorFloat();
    return v.length !== 2 || (a.push_back(v[0]), a.push_back(v[1])), a;
  },
  We = class {
    constructor(o) {
      L(this, '_canvas');
      L(this, '_context', null);
      L(this, '_eventManager');
      L(this, '_animationFrameId', null);
      L(this, '_frameManager');
      L(this, '_dotLottieCore', null);
      L(this, '_wasmModule', null);
      L(this, '_renderConfig', {});
      L(this, '_isFrozen', !1);
      L(this, '_backgroundColor', null);
      (this._canvas = o.canvas),
        (this._context = this._canvas.getContext('2d')),
        (this._eventManager = new je()),
        (this._frameManager = new Ie()),
        (this._renderConfig = o.renderConfig ?? {}),
        ne
          .load()
          .then((a) => {
            (this._wasmModule = a),
              (this._dotLottieCore = new a.DotLottiePlayer({
                autoplay: o.autoplay ?? !1,
                backgroundColor: 0,
                loopAnimation: o.loop ?? !1,
                mode: ct(o.mode ?? 'forward', a),
                segment: dt(o.segment ?? [], a),
                speed: o.speed ?? 1,
                useFrameInterpolation: o.useFrameInterpolation ?? !0,
                marker: o.marker ?? '',
                layout: o.layout ? { align: ut(o.layout.align, a), fit: lt(o.layout.fit, a) } : a.createDefaultLayout(),
              })),
              o.data ? this._loadFromData(o.data) : o.src && this._loadFromSrc(o.src),
              o.backgroundColor && this.setBackgroundColor(o.backgroundColor);
          })
          .catch((a) => {
            this._eventManager.dispatch({ type: 'loadError', error: new Error(`Failed to load wasm module: ${a}`) });
          });
    }
    _loadFromSrc(o) {
      async function a() {
        let _ = await fetch(o);
        if (!_.ok) throw new Error(`Failed to fetch the animation data from URL: ${o}. ${_.status}: ${_.statusText}`);
        let m = (_.headers.get('content-type') ?? '').trim(),
          k;
        return (
          ['application/json', 'text/plain'].some((b) => m.startsWith(b))
            ? (k = await _.text())
            : (k = await _.arrayBuffer()),
          k
        );
      }
      a()
        .then((_) => {
          this._loadFromData(_);
        })
        .catch((_) => {
          this._eventManager.dispatch({
            type: 'loadError',
            error: new Error(`Failed to load animation data from URL: ${o}. ${_}`),
          });
        });
    }
    _loadFromData(o) {
      if (this._dotLottieCore === null) return;
      let a = this._canvas.width,
        _ = this._canvas.height,
        m = !1;
      if (typeof o == 'string') m = this._dotLottieCore.loadAnimationData(o, a, _);
      else if (o instanceof ArrayBuffer) m = this._dotLottieCore.loadDotLottieData(o, a, _);
      else if (typeof o == 'object') m = this._dotLottieCore.loadAnimationData(JSON.stringify(o), a, _);
      else {
        this._eventManager.dispatch({
          type: 'loadError',
          error: new Error('Unsupported data type for animation data. Expected a string or ArrayBuffer.'),
        });
        return;
      }
      m
        ? (this._eventManager.dispatch({ type: 'load' }),
          at && this.resize(),
          this._eventManager.dispatch({ type: 'frame', currentFrame: this._dotLottieCore.currentFrame() }),
          this._render(),
          this._dotLottieCore.config().autoplay &&
            (this._dotLottieCore.play(),
            this._dotLottieCore.isPlaying()
              ? (this._eventManager.dispatch({ type: 'play' }),
                (this._animationFrameId = this._frameManager.requestAnimationFrame(this._draw.bind(this))))
              : console.error('something went wrong, the animation was suppose to autoplay')))
        : this._eventManager.dispatch({ type: 'loadError', error: new Error('Failed to load animation data') });
    }
    get activeAnimationId() {
      return this._dotLottieCore?.activeAnimationId();
    }
    get activeThemeId() {
      return this._dotLottieCore?.activeThemeId();
    }
    get layout() {
      let o = this._dotLottieCore?.config().layout;
      if (o)
        return {
          align: [o.align.get(0), o.align.get(1)],
          fit: (() => {
            switch (o.fit) {
              case this._wasmModule?.Fit.Contain:
                return 'contain';
              case this._wasmModule?.Fit.Cover:
                return 'cover';
              case this._wasmModule?.Fit.Fill:
                return 'fill';
              case this._wasmModule?.Fit.FitHeight:
                return 'fit-height';
              case this._wasmModule?.Fit.FitWidth:
                return 'fit-width';
              case this._wasmModule?.Fit.None:
                return 'none';
              default:
                return 'contain';
            }
          })(),
        };
    }
    get marker() {
      return this._dotLottieCore?.config().marker;
    }
    get manifest() {
      try {
        let o = this._dotLottieCore?.manifestString();
        if (this._dotLottieCore === null || !o) return null;
        let a = JSON.parse(o);
        return Object.keys(a).length === 0 ? null : a;
      } catch {
        return null;
      }
    }
    get renderConfig() {
      return this._renderConfig;
    }
    get segment() {
      let o = this._dotLottieCore?.config().segment;
      if (o && o.size() === 2) return [o.get(0), o.get(1)];
    }
    get loop() {
      return this._dotLottieCore?.config().loopAnimation ?? !1;
    }
    get mode() {
      let o = this._dotLottieCore?.config().mode;
      return o === this._wasmModule?.Mode.Reverse
        ? 'reverse'
        : o === this._wasmModule?.Mode.Bounce
        ? 'bounce'
        : o === this._wasmModule?.Mode.ReverseBounce
        ? 'reverse-bounce'
        : 'forward';
    }
    get isFrozen() {
      return this._isFrozen;
    }
    get backgroundColor() {
      return this._backgroundColor ?? '';
    }
    get autoplay() {
      return this._dotLottieCore?.config().autoplay ?? !1;
    }
    get useFrameInterpolation() {
      return this._dotLottieCore?.config().useFrameInterpolation ?? !1;
    }
    get speed() {
      return this._dotLottieCore?.config().speed ?? 0;
    }
    get isLoaded() {
      return this._dotLottieCore?.isLoaded() ?? !1;
    }
    get isPlaying() {
      return this._dotLottieCore?.isPlaying() ?? !1;
    }
    get isPaused() {
      return this._dotLottieCore?.isPaused() ?? !1;
    }
    get isStopped() {
      return this._dotLottieCore?.isStopped() ?? !1;
    }
    get currentFrame() {
      return this._dotLottieCore?.currentFrame() ?? 0;
    }
    get loopCount() {
      return this._dotLottieCore?.loopCount() ?? 0;
    }
    get totalFrames() {
      return this._dotLottieCore?.totalFrames() ?? 0;
    }
    get duration() {
      return this._dotLottieCore?.duration() ?? 0;
    }
    get segmentDuration() {
      return this._dotLottieCore?.segmentDuration() ?? 0;
    }
    get canvas() {
      return this._canvas;
    }
    load(o) {
      this._dotLottieCore === null ||
        this._wasmModule === null ||
        (this._dotLottieCore.setConfig({
          autoplay: o.autoplay ?? !1,
          backgroundColor: 0,
          loopAnimation: o.loop ?? !1,
          mode: ct(o.mode ?? 'forward', this._wasmModule),
          segment: dt(o.segment ?? [], this._wasmModule),
          speed: o.speed ?? 1,
          useFrameInterpolation: o.useFrameInterpolation ?? !0,
          marker: o.marker ?? '',
          layout: o.layout
            ? { align: ut(o.layout.align, this._wasmModule), fit: lt(o.layout.fit, this._wasmModule) }
            : this._wasmModule.createDefaultLayout(),
        }),
        o.data ? this._loadFromData(o.data) : o.src && this._loadFromSrc(o.src),
        this.setBackgroundColor(o.backgroundColor ?? ''));
    }
    _render() {
      if (this._dotLottieCore === null || this._context === null) return !1;
      if (this._dotLottieCore.render()) {
        let a = this._dotLottieCore.buffer(),
          _ = new Uint8ClampedArray(a, 0, this._canvas.width * this._canvas.height * 4),
          m = null;
        return (
          typeof ImageData > 'u'
            ? ((m = this._context.createImageData(this._canvas.width, this._canvas.height)), m.data.set(_))
            : (m = new ImageData(_, this._canvas.width, this._canvas.height)),
          this._context.putImageData(m, 0, 0),
          this._eventManager.dispatch({ type: 'render', currentFrame: this._dotLottieCore.currentFrame() }),
          !0
        );
      }
      return !1;
    }
    _draw() {
      if (this._dotLottieCore === null || this._context === null || !this._dotLottieCore.isPlaying()) return;
      let o = this._dotLottieCore.requestFrame();
      this._dotLottieCore.setFrame(o) &&
        (this._eventManager.dispatch({ type: 'frame', currentFrame: this._dotLottieCore.currentFrame() }),
        this._render() &&
          this._dotLottieCore.isComplete() &&
          (this._dotLottieCore.config().loopAnimation
            ? this._eventManager.dispatch({ type: 'loop', loopCount: this._dotLottieCore.loopCount() })
            : this._eventManager.dispatch({ type: 'complete' }))),
        (this._animationFrameId = this._frameManager.requestAnimationFrame(this._draw.bind(this)));
    }
    play() {
      if (this._dotLottieCore === null) return;
      let o = this._dotLottieCore.play();
      (this._isFrozen = !1),
        o &&
          (this._eventManager.dispatch({ type: 'play' }),
          (this._animationFrameId = this._frameManager.requestAnimationFrame(this._draw.bind(this))));
    }
    pause() {
      if (this._dotLottieCore === null) return;
      this._dotLottieCore.pause() && this._eventManager.dispatch({ type: 'pause' });
    }
    stop() {
      if (this._dotLottieCore === null) return;
      this._dotLottieCore.stop() &&
        (this._eventManager.dispatch({ type: 'frame', currentFrame: this._dotLottieCore.currentFrame() }),
        this._render(),
        this._eventManager.dispatch({ type: 'stop' }));
    }
    setFrame(o) {
      if (this._dotLottieCore === null || o < 0 || o > this._dotLottieCore.totalFrames()) return;
      this._dotLottieCore.seek(o) &&
        (this._eventManager.dispatch({ type: 'frame', currentFrame: this._dotLottieCore.currentFrame() }),
        this._render());
    }
    setSpeed(o) {
      this._dotLottieCore !== null && this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), speed: o });
    }
    setBackgroundColor(o) {
      this._dotLottieCore !== null &&
        (this._canvas instanceof HTMLCanvasElement && (this._canvas.style.backgroundColor = o),
        (this._backgroundColor = o));
    }
    setLoop(o) {
      this._dotLottieCore !== null &&
        this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), loopAnimation: o });
    }
    setUseFrameInterpolation(o) {
      this._dotLottieCore !== null &&
        this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), useFrameInterpolation: o });
    }
    addEventListener(o, a) {
      this._eventManager.addEventListener(o, a);
    }
    removeEventListener(o, a) {
      this._eventManager.removeEventListener(o, a);
    }
    destroy() {
      this._dotLottieCore?.delete(),
        (this._dotLottieCore = null),
        (this._context = null),
        this._eventManager.dispatch({ type: 'destroy' }),
        this._eventManager.removeAllEventListeners();
    }
    freeze() {
      this._animationFrameId !== null &&
        (this._frameManager.cancelAnimationFrame(this._animationFrameId),
        (this._animationFrameId = null),
        (this._isFrozen = !0),
        this._eventManager.dispatch({ type: 'freeze' }));
    }
    unfreeze() {
      this._animationFrameId === null &&
        ((this._animationFrameId = this._frameManager.requestAnimationFrame(this._draw.bind(this))),
        (this._isFrozen = !1),
        this._eventManager.dispatch({ type: 'unfreeze' }));
    }
    resize() {
      if (at && this._canvas instanceof HTMLCanvasElement) {
        let a = this._renderConfig.devicePixelRatio || window.devicePixelRatio || 1,
          { height: _, width: m } = this._canvas.getBoundingClientRect();
        (this._canvas.width = m * a), (this._canvas.height = _ * a);
      }
      this._dotLottieCore?.resize(this._canvas.width, this._canvas.height) && this._render();
    }
    setSegment(o, a) {
      this._dotLottieCore === null ||
        this._wasmModule === null ||
        this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), segment: dt([o, a], this._wasmModule) });
    }
    setMode(o) {
      this._dotLottieCore === null ||
        this._wasmModule === null ||
        this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), mode: ct(o, this._wasmModule) });
    }
    setRenderConfig(o) {
      this._renderConfig = o;
    }
    loadAnimation(o) {
      if (this._dotLottieCore === null) return;
      this._dotLottieCore.loadAnimation(o, this._canvas.width, this._canvas.height)
        ? (this._eventManager.dispatch({ type: 'load' }), this.resize())
        : this._eventManager.dispatch({ type: 'loadError', error: new Error(`Failed to animation :${o}`) });
    }
    setMarker(o) {
      this._dotLottieCore !== null && this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), marker: o });
    }
    markers() {
      let o = this._dotLottieCore?.markers();
      if (o) {
        let a = [];
        for (let _ = 0; _ < o.size(); _ += 1) {
          let m = o.get(_);
          a.push({ name: m.name, time: m.time, duration: m.duration });
        }
        return a;
      }
      return [];
    }
    loadTheme(o) {
      if (this._dotLottieCore === null) return !1;
      let a = this._dotLottieCore.loadTheme(o);
      return this._render(), a;
    }
    loadThemeData(o) {
      if (this._dotLottieCore === null) return !1;
      let a = this._dotLottieCore.loadThemeData(o);
      return this._render(), a;
    }
    setLayout(o) {
      this._dotLottieCore === null ||
        this._wasmModule === null ||
        this._dotLottieCore.setConfig({
          ...this._dotLottieCore.config(),
          layout: { align: ut(o.align, this._wasmModule), fit: lt(o.fit, this._wasmModule) },
        });
    }
    setViewport(o, a, _, m) {
      return this._dotLottieCore === null ? !1 : this._dotLottieCore.setViewport(o, a, _, m);
    }
    static setWasmUrl(o) {
      ne.setWasmUrl(o);
    }
  };
var z = new Map(),
  Ki = (v) => {
    let o = v.data,
      { id: a, method: _, params: m } = o,
      k = (g) => {
        let J = { result: g, id: a };
        self.postMessage(J);
      },
      b = (g) => {
        let J = { error: g, id: a };
        self.postMessage(J);
      };
    try {
      if (_ === 'create' && m?.config) {
        if (!m.id) return b({ message: 'Missing id', code: -32602 });
        let g = new We(m.config);
        z.set(m.id, g),
          [
            'complete',
            'frame',
            'load',
            'loadError',
            'loop',
            'pause',
            'play',
            'stop',
            'destroy',
            'freeze',
            'unfreeze',
            'render',
          ].forEach((we) => {
            g.addEventListener(we, (Ee) => {
              let re = { id: a, result: { event: we, details: Ee } };
              self.postMessage(re);
            });
          }),
          k({ success: !0 });
      }
      if (_ === 'play') {
        if (!m?.id) return b({ message: 'Missing id', code: -32602 });
        let g = z.get(m.id);
        if (!g) return b({ message: 'DotLottie instance not found', code: -32602 });
        g.play(), k({ success: !0 });
      }
      if (_ === 'pause') {
        if (!m?.id) return b({ message: 'Missing id', code: -32602 });
        let g = z.get(m.id);
        if (!g) return b({ message: 'DotLottie instance not found', code: -32602 });
        g.pause(), k({ success: !0 });
      }
      if (_ === 'stop') {
        if (!m?.id) return b({ message: 'Missing id', code: -32602 });
        let g = z.get(m.id);
        if (!g) return b({ message: 'DotLottie instance not found', code: -32602 });
        g.stop(), k({ success: !0 });
      }
      if (_ === 'destroy') {
        if (!m?.id) return b({ message: 'Missing id', code: -32602 });
        let g = z.get(m.id);
        if (!g) return b({ message: 'DotLottie instance not found', code: -32602 });
        g.destroy(), z.delete(m.id), k({ success: !0 });
      }
      if (_ === 'setSpeed') {
        if (!m?.id) return b({ message: 'Missing id', code: -32602 });
        let g = z.get(m.id);
        if (!g) return b({ message: 'DotLottie instance not found', code: -32602 });
        if (typeof m.speed != 'number') return b({ message: 'Missing speed', code: -32602 });
        g.setSpeed(m.speed), k({ success: !0 });
      }
      if (_ === 'setMode') {
        if (!m?.id) return b({ message: 'Missing id', code: -32602 });
        let g = z.get(m.id);
        if (!g) return b({ message: 'DotLottie instance not found', code: -32602 });
        if (typeof m.mode != 'string') return b({ message: 'Missing mode', code: -32602 });
        g.setMode(m.mode), k({ success: !0 });
      }
      if (_ === 'setFrame') {
        if (!m?.id) return b({ message: 'Missing id', code: -32602 });
        let g = z.get(m.id);
        if (!g) return b({ message: 'DotLottie instance not found', code: -32602 });
        if (typeof m.frame != 'number') return b({ message: 'Missing frame', code: -32602 });
        g.setFrame(m.frame), k({ success: !0 });
      }
      if (_ === 'load') {
        if (!m?.id) return b({ message: 'Missing id', code: -32602 });
        let g = z.get(m.id);
        if (!g) return b({ message: 'DotLottie instance not found', code: -32602 });
        if (!m.config) return b({ message: 'Missing config', code: -32602 });
        g.load(m.config), k({ success: !0 });
      }
      if (_ === 'resize') {
        if (!m?.id) return b({ message: 'Missing id', code: -32602 });
        let g = z.get(m.id);
        if (!g) return b({ message: 'DotLottie instance not found', code: -32602 });
        if (typeof m.width != 'number') return b({ message: 'Missing width', code: -32602 });
        if (typeof m.height != 'number') return b({ message: 'Missing height', code: -32602 });
        (g.canvas.width = m.width), (g.canvas.height = m.height), g.resize(), k({ success: !0 });
      }
      b({ message: 'Method not found', code: -32601 });
    } catch (g) {
      b({ message: 'Internal error', data: g instanceof Error ? g.message : g, code: -32603 });
    }
  };
self.addEventListener('message', Ki);
var Qi = '',
  To = Qi;

export { To as default };
