/**
 * This is a worker script for dotlottie.
 * Do not modify this file directly.
 * As it's generated by the build process.
 */

var Pn = Object.defineProperty;
var An = (s, n, a) => (n in s ? Pn(s, n, { enumerable: !0, configurable: !0, writable: !0, value: a }) : (s[n] = a));
var x = (s, n, a) => An(s, typeof n != 'symbol' ? n + '' : n, a);
var qe = class {
    requestAnimationFrame(n) {
      return requestAnimationFrame(n);
    }
    cancelAnimationFrame(n) {
      cancelAnimationFrame(n);
    }
  },
  et = class {
    constructor() {
      x(this, '_lastHandleId', 0);
      x(this, '_lastImmediate', null);
    }
    requestAnimationFrame(n) {
      return (
        this._lastHandleId >= Number.MAX_SAFE_INTEGER && (this._lastHandleId = 0),
        (this._lastHandleId += 1),
        (this._lastImmediate = setImmediate(() => {
          n(Date.now());
        })),
        this._lastHandleId
      );
    }
    cancelAnimationFrame(n) {
      this._lastImmediate && clearImmediate(this._lastImmediate);
    }
  },
  ke = class {
    constructor() {
      x(this, '_strategy');
      this._strategy = typeof requestAnimationFrame == 'function' ? new qe() : new et();
    }
    requestAnimationFrame(n) {
      return this._strategy.requestAnimationFrame(n);
    }
    cancelAnimationFrame(n) {
      this._strategy.cancelAnimationFrame(n);
    }
  };
var le = typeof window < 'u' && typeof window.document < 'u';
var ge = {
  name: '@lottiefiles/dotlottie-web',
  version: '0.27.0',
  type: 'module',
  description: 'Lottie and DotLottie player for the web',
  repository: { type: 'git', url: 'git+https://github.com/LottieFiles/dotlottie-web.git', directory: 'packages/web' },
  homepage: 'https://github.com/LottieFiles/dotlottie-web#readme',
  bugs: 'https://github.com/LottieFiles/dotlottie-web/issues',
  author: 'LottieFiles',
  contributors: ['Abdelrahman Ashraf <a.theashraf@gmail.com>'],
  license: 'MIT',
  main: 'dist/index.cjs',
  module: 'dist/index.js',
  types: 'dist/index.d.ts',
  files: ['dist'],
  keywords: ['dotlottie', 'lottie', 'player', 'animation', 'web', 'canvas', 'javascript', 'thorvg'],
  scripts: {
    build: 'tsup',
    dev: 'tsup --watch',
    lint: 'eslint --fix .',
    'stats:eslint': 'cross-env TIMING=1 eslint .',
    'stats:ts': 'tsc -p tsconfig.build.json --extendedDiagnostics',
    test: 'vitest run --browser.headless',
    'test:coverage': 'vitest run --browser.headless --coverage',
    'test:watch': 'vitest',
    'type-check': 'tsc --noEmit',
  },
  devDependencies: {
    '@types/node': '^20.10.5',
    '@vitest/browser': '^1.2.2 ',
    '@vitest/coverage-istanbul': '^1.2.2',
    'cross-env': '7.0.3',
    tsup: '8.1.0',
    typescript: '5.0.4',
    vitest: '^1.2.2',
    webdriverio: '^8.32.0',
  },
  publishConfig: { access: 'public' },
};
var Rn = (() => {
    let s = typeof document < 'u' ? document.currentScript?.src : void 0;
    return function (n = {}) {
      var a = n,
        u,
        w,
        T = new Promise((e, t) => {
          (u = e), (w = t);
        }),
        B = Object.assign({}, a),
        K = './this.program',
        j = '';
      typeof document < 'u' && document.currentScript && (j = document.currentScript.src),
        s && (j = s),
        j.startsWith('blob:') ? (j = '') : (j = j.substr(0, j.replace(/[?#].*/, '').lastIndexOf('/') + 1));
      var Ht = a.print || console.log.bind(console),
        re = a.printErr || console.error.bind(console);
      Object.assign(a, B), (B = null), a.thisProgram && (K = a.thisProgram);
      var ue;
      a.wasmBinary && (ue = a.wasmBinary);
      var _e,
        ot = !1,
        X,
        b,
        ae,
        de,
        A,
        L,
        it,
        st;
      function lt() {
        var e = _e.buffer;
        (a.HEAP8 = X = new Int8Array(e)),
          (a.HEAP16 = ae = new Int16Array(e)),
          (a.HEAPU8 = b = new Uint8Array(e)),
          (a.HEAPU16 = de = new Uint16Array(e)),
          (a.HEAP32 = A = new Int32Array(e)),
          (a.HEAPU32 = L = new Uint32Array(e)),
          (a.HEAPF32 = it = new Float32Array(e)),
          (a.HEAPF64 = st = new Float64Array(e));
      }
      var ut = [],
        dt = [],
        ct = [];
      function Vt() {
        var e = a.preRun.shift();
        ut.unshift(e);
      }
      var Z = 0,
        ce = null;
      function Ee(e) {
        throw (
          (a.onAbort?.(e),
          (e = 'Aborted(' + e + ')'),
          re(e),
          (ot = !0),
          (e = new WebAssembly.RuntimeError(e + '. Build with -sASSERTIONS for more info.')),
          w(e),
          e)
        );
      }
      var ht = (e) => e.startsWith('data:application/octet-stream;base64,'),
        oe;
      if (((oe = 'DotLottiePlayer.wasm'), !ht(oe))) {
        var pt = oe;
        oe = a.locateFile ? a.locateFile(pt, j) : j + pt;
      }
      function mt(e) {
        if (e == oe && ue) return new Uint8Array(ue);
        throw 'both async and sync fetching of the wasm failed';
      }
      function Yt(e) {
        return ue || typeof fetch != 'function'
          ? Promise.resolve().then(() => mt(e))
          : fetch(e, { credentials: 'same-origin' })
              .then((t) => {
                if (!t.ok) throw `failed to load wasm binary file at '${e}'`;
                return t.arrayBuffer();
              })
              .catch(() => mt(e));
      }
      function ft(e, t, r) {
        return Yt(e)
          .then((o) => WebAssembly.instantiate(o, t))
          .then(r, (o) => {
            re(`failed to asynchronously prepare wasm: ${o}`), Ee(o);
          });
      }
      function Nt(e, t) {
        var r = oe;
        return ue || typeof WebAssembly.instantiateStreaming != 'function' || ht(r) || typeof fetch != 'function'
          ? ft(r, e, t)
          : fetch(r, { credentials: 'same-origin' }).then((o) =>
              WebAssembly.instantiateStreaming(o, e).then(t, function (i) {
                return (
                  re(`wasm streaming compile failed: ${i}`),
                  re('falling back to ArrayBuffer instantiation'),
                  ft(r, e, t)
                );
              }),
            );
      }
      var Oe = (e) => {
          for (; 0 < e.length; ) e.shift()(a);
        },
        vt = typeof TextDecoder < 'u' ? new TextDecoder('utf8') : void 0,
        Q = (e, t, r) => {
          var o = t + r;
          for (r = t; e[r] && !(r >= o); ) ++r;
          if (16 < r - t && e.buffer && vt) return vt.decode(e.subarray(t, r));
          for (o = ''; t < r; ) {
            var i = e[t++];
            if (i & 128) {
              var l = e[t++] & 63;
              if ((i & 224) == 192) o += String.fromCharCode(((i & 31) << 6) | l);
              else {
                var h = e[t++] & 63;
                (i =
                  (i & 240) == 224
                    ? ((i & 15) << 12) | (l << 6) | h
                    : ((i & 7) << 18) | (l << 12) | (h << 6) | (e[t++] & 63)),
                  65536 > i
                    ? (o += String.fromCharCode(i))
                    : ((i -= 65536), (o += String.fromCharCode(55296 | (i >> 10), 56320 | (i & 1023))));
              }
            } else o += String.fromCharCode(i);
          }
          return o;
        };
      class Gt {
        constructor(t) {
          this.ya = t - 24;
        }
      }
      var yt = 0,
        gt = (e) => {
          for (var t = 0, r = 0; r < e.length; ++r) {
            var o = e.charCodeAt(r);
            127 >= o ? t++ : 2047 >= o ? (t += 2) : 55296 <= o && 57343 >= o ? ((t += 4), ++r) : (t += 3);
          }
          return t;
        },
        wt = (e, t, r, o) => {
          if (0 < o) {
            o = r + o - 1;
            for (var i = 0; i < e.length; ++i) {
              var l = e.charCodeAt(i);
              if (55296 <= l && 57343 >= l) {
                var h = e.charCodeAt(++i);
                l = (65536 + ((l & 1023) << 10)) | (h & 1023);
              }
              if (127 >= l) {
                if (r >= o) break;
                t[r++] = l;
              } else {
                if (2047 >= l) {
                  if (r + 1 >= o) break;
                  t[r++] = 192 | (l >> 6);
                } else {
                  if (65535 >= l) {
                    if (r + 2 >= o) break;
                    t[r++] = 224 | (l >> 12);
                  } else {
                    if (r + 3 >= o) break;
                    (t[r++] = 240 | (l >> 18)), (t[r++] = 128 | ((l >> 12) & 63));
                  }
                  t[r++] = 128 | ((l >> 6) & 63);
                }
                t[r++] = 128 | (l & 63);
              }
            }
            t[r] = 0;
          }
        },
        Ce = {},
        Be = (e) => {
          for (; e.length; ) {
            var t = e.pop();
            e.pop()(t);
          }
        };
      function he(e) {
        return this.fromWireType(L[e >> 2]);
      }
      var U = {},
        Y = {},
        pe = {},
        q,
        N = (e, t, r) => {
          function o(c) {
            if (((c = r(c)), c.length !== e.length)) throw new q('Mismatched type converter count');
            for (var m = 0; m < e.length; ++m) $(e[m], c[m]);
          }
          e.forEach(function (c) {
            pe[c] = t;
          });
          var i = Array(t.length),
            l = [],
            h = 0;
          t.forEach((c, m) => {
            Y.hasOwnProperty(c)
              ? (i[m] = Y[c])
              : (l.push(c),
                U.hasOwnProperty(c) || (U[c] = []),
                U[c].push(() => {
                  (i[m] = Y[c]), ++h, h === l.length && o(i);
                }));
          }),
            l.length === 0 && o(i);
        },
        _t,
        P = (e) => {
          for (var t = ''; b[e]; ) t += _t[b[e++]];
          return t;
        },
        y;
      function Et(e, t, r = {}) {
        var o = t.name;
        if (!e) throw new y(`type "${o}" must have a positive integer typeid pointer`);
        if (Y.hasOwnProperty(e)) {
          if (r.ib) return;
          throw new y(`Cannot register type '${o}' twice`);
        }
        (Y[e] = t), delete pe[e], U.hasOwnProperty(e) && ((t = U[e]), delete U[e], t.forEach((i) => i()));
      }
      var Me = (e) => {
          throw new y(e.ma.za.xa.name + ' instance already deleted');
        },
        ee = !1,
        Le = () => {},
        be = (e, t, r) => (t === r ? e : r.Ca === void 0 ? null : ((e = be(e, t, r.Ca)), e === null ? null : r.ab(e))),
        We = {},
        G = [],
        Fe = () => {
          for (; G.length; ) {
            var e = G.pop();
            (e.ma.Ka = !1), e.delete();
          }
        },
        ie,
        te = {},
        Ct = (e, t) => {
          if (t === void 0) throw new y('ptr should not be undefined');
          for (; e.Ca; ) (t = e.Na(t)), (e = e.Ca);
          return te[t];
        },
        me = (e, t) => {
          if (!t.za || !t.ya) throw new q('makeClassHandle requires ptr and ptrType');
          if (!!t.Da != !!t.Aa) throw new q('Both smartPtrType and smartPtr must be specified');
          return (t.count = { value: 1 }), W(Object.create(e, { ma: { value: t, writable: !0 } }));
        },
        W = (e) =>
          typeof FinalizationRegistry > 'u'
            ? ((W = (t) => t), e)
            : ((ee = new FinalizationRegistry((t) => {
                (t = t.ma), --t.count.value, t.count.value === 0 && (t.Aa ? t.Da.Fa(t.Aa) : t.za.xa.Fa(t.ya));
              })),
              (W = (t) => {
                var r = t.ma;
                return r.Aa && ee.register(t, { ma: r }, t), t;
              }),
              (Le = (t) => {
                ee.unregister(t);
              }),
              W(e)),
        se = (e, t) => Object.defineProperty(t, 'name', { value: e }),
        xe = (e, t, r) => {
          if (e[t].Ba === void 0) {
            var o = e[t];
            (e[t] = function (...i) {
              if (!e[t].Ba.hasOwnProperty(i.length))
                throw new y(
                  `Function '${r}' called with an invalid number of arguments (${i.length}) - expects one of (${e[t].Ba})!`,
                );
              return e[t].Ba[i.length].apply(this, i);
            }),
              (e[t].Ba = []),
              (e[t].Ba[o.Oa] = o);
          }
        },
        Ie = (e, t, r) => {
          if (a.hasOwnProperty(e)) {
            if (r === void 0 || (a[e].Ba !== void 0 && a[e].Ba[r] !== void 0))
              throw new y(`Cannot register public name '${e}' twice`);
            if ((xe(a, e, e), a.hasOwnProperty(r)))
              throw new y(`Cannot register multiple overloads of a function with the same number of arguments (${r})!`);
            a[e].Ba[r] = t;
          } else (a[e] = t), r !== void 0 && (a[e].vb = r);
        },
        Mt = (e) => {
          if (e === void 0) return '_unknown';
          e = e.replace(/[^a-zA-Z0-9_]/g, '$');
          var t = e.charCodeAt(0);
          return 48 <= t && 57 >= t ? `_${e}` : e;
        },
        Pe = (e, t, r) => {
          for (; t !== r; ) {
            if (!t.Na) throw new y(`Expected null or instance of ${r.name}, got an instance of ${t.name}`);
            (e = t.Na(e)), (t = t.Ca);
          }
          (Y[e] = t), delete pe[e], U.hasOwnProperty(e) && ((t = U[e]), delete U[e], t.forEach((o) => o()));
        };
      function $(e, t, r = {}) {
        if (!('argPackAdvance' in t)) throw new TypeError('registerType registeredInstance requires argPackAdvance');
        return Et(e, t, r);
      }
      var Me = (e) => {
          throw new y(e.ma.za.xa.name + ' instance already deleted');
        },
        ee = !1,
        Le = () => {},
        be = (e, t, r) => (t === r ? e : r.Ca === void 0 ? null : ((e = be(e, t, r.Ca)), e === null ? null : r.ab(e))),
        We = {},
        G = [],
        Fe = () => {
          for (; G.length; ) {
            var e = G.pop();
            (e.ma.Ka = !1), e.delete();
          }
        },
        ie,
        te = {},
        Ct = (e, t) => {
          if (t === void 0) throw new y('ptr should not be undefined');
          for (; e.Ca; ) (t = e.Na(t)), (e = e.Ca);
          return te[t];
        },
        me = (e, t) => {
          if (!t.za || !t.ya) throw new q('makeClassHandle requires ptr and ptrType');
          if (!!t.Da != !!t.Aa) throw new q('Both smartPtrType and smartPtr must be specified');
          return (t.count = { value: 1 }), W(Object.create(e, { ma: { value: t, writable: !0 } }));
        },
        W = (e) =>
          typeof FinalizationRegistry > 'u'
            ? ((W = (t) => t), e)
            : ((ee = new FinalizationRegistry((t) => {
                (t = t.ma), --t.count.value, t.count.value === 0 && (t.Aa ? t.Da.Fa(t.Aa) : t.za.xa.Fa(t.ya));
              })),
              (W = (t) => {
                var r = t.ma;
                return r.Aa && ee.register(t, { ma: r }, t), t;
              }),
              (Le = (t) => {
                ee.unregister(t);
              }),
              W(e));
      function fe() {}
      var se = (e, t) => Object.defineProperty(t, 'name', { value: e }),
        xe = (e, t, r) => {
          if (e[t].Ba === void 0) {
            var o = e[t];
            (e[t] = function (...i) {
              if (!e[t].Ba.hasOwnProperty(i.length))
                throw new y(
                  `Function '${r}' called with an invalid number of arguments (${i.length}) - expects one of (${e[t].Ba})!`,
                );
              return e[t].Ba[i.length].apply(this, i);
            }),
              (e[t].Ba = []),
              (e[t].Ba[o.Oa] = o);
          }
        },
        Ie = (e, t, r) => {
          if (a.hasOwnProperty(e)) {
            if (r === void 0 || (a[e].Ba !== void 0 && a[e].Ba[r] !== void 0))
              throw new y(`Cannot register public name '${e}' twice`);
            if ((xe(a, e, e), a.hasOwnProperty(r)))
              throw new y(`Cannot register multiple overloads of a function with the same number of arguments (${r})!`);
            a[e].Ba[r] = t;
          } else (a[e] = t), r !== void 0 && (a[e].vb = r);
        },
        Mt = (e) => {
          if (e === void 0) return '_unknown';
          e = e.replace(/[^a-zA-Z0-9_]/g, '$');
          var t = e.charCodeAt(0);
          return 48 <= t && 57 >= t ? `_${e}` : e;
        };
      function Lt(e, t, r, o, i, l, h, c) {
        (this.name = e),
          (this.constructor = t),
          (this.La = r),
          (this.Fa = o),
          (this.Ca = i),
          (this.cb = l),
          (this.Na = h),
          (this.ab = c),
          (this.kb = []);
      }
      var Pe = (e, t, r) => {
        for (; t !== r; ) {
          if (!t.Na) throw new y(`Expected null or instance of ${r.name}, got an instance of ${t.name}`);
          (e = t.Na(e)), (t = t.Ca);
        }
        return e;
      };
      function Kt(e, t) {
        if (t === null) {
          if (this.Ta) throw new y(`null is not a valid ${this.name}`);
          return 0;
        }
        if (!t.ma) throw new y(`Cannot pass "${Ge(t)}" as a ${this.name}`);
        if (!t.ma.ya) throw new y(`Cannot pass deleted object as a pointer of type ${this.name}`);
        return Pe(t.ma.ya, t.ma.za.xa, this.xa);
      }
      function Xt(e, t) {
        if (t === null) {
          if (this.Ta) throw new y(`null is not a valid ${this.name}`);
          if (this.Qa) {
            var r = this.Ua();
            return e !== null && e.push(this.Fa, r), r;
          }
          return 0;
        }
        if (!t || !t.ma) throw new y(`Cannot pass "${Ge(t)}" as a ${this.name}`);
        if (!t.ma.ya) throw new y(`Cannot pass deleted object as a pointer of type ${this.name}`);
        if (!this.Pa && t.ma.za.Pa)
          throw new y(
            `Cannot convert argument of type ${t.ma.Da ? t.ma.Da.name : t.ma.za.name} to parameter type ${this.name}`,
          );
        if (((r = Pe(t.ma.ya, t.ma.za.xa, this.xa)), this.Qa)) {
          if (t.ma.Aa === void 0) throw new y('Passing raw pointer to smart pointer is illegal');
          switch (this.pb) {
            case 0:
              if (t.ma.Da === this) r = t.ma.Aa;
              else
                throw new y(
                  `Cannot convert argument of type ${t.ma.Da ? t.ma.Da.name : t.ma.za.name} to parameter type ${
                    this.name
                  }`,
                );
              break;
            case 1:
              r = t.ma.Aa;
              break;
            case 2:
              if (t.ma.Da === this) r = t.ma.Aa;
              else {
                var o = t.clone();
                (r = this.lb(
                  r,
                  Te(() => o.delete()),
                )),
                  e !== null && e.push(this.Fa, r);
              }
              break;
            default:
              throw new y('Unsupporting sharing policy');
          }
        }
        return r;
      }
      function Zt(e, t) {
        if (t === null) {
          if (this.Ta) throw new y(`null is not a valid ${this.name}`);
          return 0;
        }
        if (!t.ma) throw new y(`Cannot pass "${Ge(t)}" as a ${this.name}`);
        if (!t.ma.ya) throw new y(`Cannot pass deleted object as a pointer of type ${this.name}`);
        if (t.ma.za.Pa) throw new y(`Cannot convert argument of type ${t.ma.za.name} to parameter type ${this.name}`);
        return Pe(t.ma.ya, t.ma.za.xa, this.xa);
      }
      function ve(e, t, r, o, i, l, h, c, m, p, f) {
        (this.name = e),
          (this.xa = t),
          (this.Ta = r),
          (this.Pa = o),
          (this.Qa = i),
          (this.jb = l),
          (this.pb = h),
          (this.Za = c),
          (this.Ua = m),
          (this.lb = p),
          (this.Fa = f),
          i || t.Ca !== void 0 ? (this.toWireType = Xt) : ((this.toWireType = o ? Kt : Zt), (this.Ea = null));
      }
      var bt = (e, t, r) => {
          if (!a.hasOwnProperty(e)) throw new q('Replacing nonexistent public symbol');
          a[e].Ba !== void 0 && r !== void 0 ? (a[e].Ba[r] = t) : ((a[e] = t), (a[e].Oa = r));
        },
        k,
        Qt = (e, t, r = []) => (
          e.includes('j') ? ((e = e.replace(/p/g, 'i')), (t = (0, a['dynCall_' + e])(t, ...r))) : (t = k.get(t)(...r)),
          t
        ),
        qt =
          (e, t) =>
          (...r) =>
            Qt(e, t, r),
        R = (e, t) => {
          e = P(e);
          var r = e.includes('j') ? qt(e, t) : k.get(t);
          if (typeof r != 'function') throw new y(`unknown function pointer with signature ${e}: ${t}`);
          return r;
        },
        Ft,
        xt = (e) => {
          e = Dt(e);
          var t = P(e);
          return V(e), t;
        },
        Ae = (e, t) => {
          function r(l) {
            i[l] || Y[l] || (pe[l] ? pe[l].forEach(r) : (o.push(l), (i[l] = !0)));
          }
          var o = [],
            i = {};
          throw (t.forEach(r), new Ft(`${e}: ` + o.map(xt).join([', '])));
        },
        je = (e, t) => {
          for (var r = [], o = 0; o < e; o++) r.push(L[(t + 4 * o) >> 2]);
          return r;
        };
      function en(e) {
        for (var t = 1; t < e.length; ++t) if (e[t] !== null && e[t].Ea === void 0) return !0;
        return !1;
      }
      function Ue(e, t, r, o, i) {
        var l = t.length;
        if (2 > l) throw new y("argTypes array size mismatch! Must at least get return value and 'this' types!");
        var h = t[1] !== null && r !== null,
          c = en(t),
          m = t[0].name !== 'void',
          p = l - 2,
          f = Array(p),
          _ = [],
          C = [];
        return se(e, function (...d) {
          if (d.length !== p) throw new y(`function ${e} called with ${d.length} arguments, expected ${p}`);
          if (((C.length = 0), (_.length = h ? 2 : 1), (_[0] = i), h)) {
            var v = t[1].toWireType(C, this);
            _[1] = v;
          }
          for (var g = 0; g < p; ++g) (f[g] = t[g + 2].toWireType(C, d[g])), _.push(f[g]);
          if (((d = o(..._)), c)) Be(C);
          else
            for (g = h ? 1 : 2; g < t.length; g++) {
              var I = g === 1 ? v : f[g - 2];
              t[g].Ea !== null && t[g].Ea(I);
            }
          return (v = m ? t[0].fromWireType(d) : void 0), v;
        });
      }
      var It = (e) => {
          e = e.trim();
          let t = e.indexOf('(');
          return t !== -1 ? e.substr(0, t) : e;
        },
        He = [],
        H = [],
        Ve = (e) => {
          9 < e && --H[e + 1] === 0 && ((H[e] = void 0), He.push(e));
        },
        Ye = (e) => {
          if (!e) throw new y('Cannot use deleted val. handle = ' + e);
          return H[e];
        },
        Te = (e) => {
          switch (e) {
            case void 0:
              return 2;
            case null:
              return 4;
            case !0:
              return 6;
            case !1:
              return 8;
            default:
              let t = He.pop() || H.length;
              return (H[t] = e), (H[t + 1] = 1), t;
          }
        },
        Pt = {
          name: 'emscripten::val',
          fromWireType: (e) => {
            var t = Ye(e);
            return Ve(e), t;
          },
          toWireType: (e, t) => Te(t),
          argPackAdvance: 8,
          readValueFromPointer: he,
          Ea: null,
        },
        tn = (e, t, r) => {
          switch (t) {
            case 1:
              return r
                ? function (o) {
                    return this.fromWireType(X[o]);
                  }
                : function (o) {
                    return this.fromWireType(b[o]);
                  };
            case 2:
              return r
                ? function (o) {
                    return this.fromWireType(ae[o >> 1]);
                  }
                : function (o) {
                    return this.fromWireType(de[o >> 1]);
                  };
            case 4:
              return r
                ? function (o) {
                    return this.fromWireType(A[o >> 2]);
                  }
                : function (o) {
                    return this.fromWireType(L[o >> 2]);
                  };
            default:
              throw new TypeError(`invalid integer width (${t}): ${e}`);
          }
        },
        Ne = (e, t) => {
          var r = Y[e];
          if (r === void 0) throw ((e = `${t} has unknown type ${xt(e)}`), new y(e));
          return r;
        },
        Ge = (e) => {
          if (e === null) return 'null';
          var t = typeof e;
          return t === 'object' || t === 'array' || t === 'function' ? e.toString() : '' + e;
        },
        nn = (e, t) => {
          switch (t) {
            case 4:
              return function (r) {
                return this.fromWireType(it[r >> 2]);
              };
            case 8:
              return function (r) {
                return this.fromWireType(st[r >> 3]);
              };
            default:
              throw new TypeError(`invalid float width (${t}): ${e}`);
          }
        },
        rn = (e, t, r) => {
          switch (t) {
            case 1:
              return r ? (o) => X[o] : (o) => b[o];
            case 2:
              return r ? (o) => ae[o >> 1] : (o) => de[o >> 1];
            case 4:
              return r ? (o) => A[o >> 2] : (o) => L[o >> 2];
            default:
              throw new TypeError(`invalid integer width (${t}): ${e}`);
          }
        },
        At = typeof TextDecoder < 'u' ? new TextDecoder('utf-16le') : void 0,
        an = (e, t) => {
          for (var r = e >> 1, o = r + t / 2; !(r >= o) && de[r]; ) ++r;
          if (((r <<= 1), 32 < r - e && At)) return At.decode(b.subarray(e, r));
          for (r = '', o = 0; !(o >= t / 2); ++o) {
            var i = ae[(e + 2 * o) >> 1];
            if (i == 0) break;
            r += String.fromCharCode(i);
          }
          return r;
        },
        on = (e, t, r) => {
          if ((r ?? (r = 2147483647), 2 > r)) return 0;
          r -= 2;
          var o = t;
          r = r < 2 * e.length ? r / 2 : e.length;
          for (var i = 0; i < r; ++i) (ae[t >> 1] = e.charCodeAt(i)), (t += 2);
          return (ae[t >> 1] = 0), t - o;
        },
        sn = (e) => 2 * e.length,
        ln = (e, t) => {
          for (var r = 0, o = ''; !(r >= t / 4); ) {
            var i = A[(e + 4 * r) >> 2];
            if (i == 0) break;
            ++r,
              65536 <= i
                ? ((i -= 65536), (o += String.fromCharCode(55296 | (i >> 10), 56320 | (i & 1023))))
                : (o += String.fromCharCode(i));
          }
          return o;
        },
        un = (e, t, r) => {
          if ((r ?? (r = 2147483647), 4 > r)) return 0;
          var o = t;
          r = o + r - 4;
          for (var i = 0; i < e.length; ++i) {
            var l = e.charCodeAt(i);
            if (55296 <= l && 57343 >= l) {
              var h = e.charCodeAt(++i);
              l = (65536 + ((l & 1023) << 10)) | (h & 1023);
            }
            if (((A[t >> 2] = l), (t += 4), t + 4 > r)) break;
          }
          return (A[t >> 2] = 0), t - o;
        },
        dn = (e) => {
          for (var t = 0, r = 0; r < e.length; ++r) {
            var o = e.charCodeAt(r);
            55296 <= o && 57343 >= o && ++r, (t += 4);
          }
          return t;
        },
        Je = [],
        cn = (e) => {
          var t = Je.length;
          return Je.push(e), t;
        },
        hn = (e, t) => {
          for (var r = Array(e), o = 0; o < e; ++o) r[o] = Ne(L[(t + 4 * o) >> 2], 'parameter ' + o);
          return r;
        },
        pn = Reflect.construct,
        Ke = {},
        Tt = () => {
          if (!Xe) {
            var e = {
                USER: 'web_user',
                LOGNAME: 'web_user',
                PATH: '/',
                PWD: '/',
                HOME: '/home/web_user',
                LANG:
                  ((typeof navigator == 'object' && navigator.languages && navigator.languages[0]) || 'C').replace(
                    '-',
                    '_',
                  ) + '.UTF-8',
                _: K || './this.program',
              },
              t;
            for (t in Ke) Ke[t] === void 0 ? delete e[t] : (e[t] = Ke[t]);
            var r = [];
            for (t in e) r.push(`${t}=${e[t]}`);
            Xe = r;
          }
          return Xe;
        },
        Xe,
        mn = [null, [], []],
        fn = () => {
          if (typeof crypto == 'object' && typeof crypto.getRandomValues == 'function')
            return (e) => crypto.getRandomValues(e);
          Ee('initRandomDevice');
        },
        Rt = (e) => (Rt = fn())(e),
        Re = (e) => e % 4 === 0 && (e % 100 !== 0 || e % 400 === 0),
        St = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31],
        $t = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
      function vn(e) {
        var t = Array(gt(e) + 1);
        return wt(e, t, 0, t.length), t;
      }
      var yn = (e, t, r, o) => {
        function i(d, v, g) {
          for (d = typeof d == 'number' ? d.toString() : d || ''; d.length < v; ) d = g[0] + d;
          return d;
        }
        function l(d, v) {
          return i(d, v, '0');
        }
        function h(d, v) {
          function g(J) {
            return 0 > J ? -1 : 0 < J ? 1 : 0;
          }
          var I;
          return (
            (I = g(d.getFullYear() - v.getFullYear())) === 0 &&
              (I = g(d.getMonth() - v.getMonth())) === 0 &&
              (I = g(d.getDate() - v.getDate())),
            I
          );
        }
        function c(d) {
          switch (d.getDay()) {
            case 0:
              return new Date(d.getFullYear() - 1, 11, 29);
            case 1:
              return d;
            case 2:
              return new Date(d.getFullYear(), 0, 3);
            case 3:
              return new Date(d.getFullYear(), 0, 2);
            case 4:
              return new Date(d.getFullYear(), 0, 1);
            case 5:
              return new Date(d.getFullYear() - 1, 11, 31);
            case 6:
              return new Date(d.getFullYear() - 1, 11, 30);
          }
        }
        function m(d) {
          var v = d.Ia;
          for (d = new Date(new Date(d.Ja + 1900, 0, 1).getTime()); 0 < v; ) {
            var g = d.getMonth(),
              I = (Re(d.getFullYear()) ? St : $t)[g];
            if (v > I - d.getDate())
              (v -= I - d.getDate() + 1),
                d.setDate(1),
                11 > g ? d.setMonth(g + 1) : (d.setMonth(0), d.setFullYear(d.getFullYear() + 1));
            else {
              d.setDate(d.getDate() + v);
              break;
            }
          }
          return (
            (g = new Date(d.getFullYear() + 1, 0, 4)),
            (v = c(new Date(d.getFullYear(), 0, 4))),
            (g = c(g)),
            0 >= h(v, d) ? (0 >= h(g, d) ? d.getFullYear() + 1 : d.getFullYear()) : d.getFullYear() - 1
          );
        }
        var p = L[(o + 40) >> 2];
        (o = {
          sb: A[o >> 2],
          rb: A[(o + 4) >> 2],
          Ra: A[(o + 8) >> 2],
          Va: A[(o + 12) >> 2],
          Sa: A[(o + 16) >> 2],
          Ja: A[(o + 20) >> 2],
          Ga: A[(o + 24) >> 2],
          Ia: A[(o + 28) >> 2],
          wb: A[(o + 32) >> 2],
          qb: A[(o + 36) >> 2],
          tb: p && p ? Q(b, p) : '',
        }),
          (r = r ? Q(b, r) : ''),
          (p = {
            '%c': '%a %b %d %H:%M:%S %Y',
            '%D': '%m/%d/%y',
            '%F': '%Y-%m-%d',
            '%h': '%b',
            '%r': '%I:%M:%S %p',
            '%R': '%H:%M',
            '%T': '%H:%M:%S',
            '%x': '%m/%d/%y',
            '%X': '%H:%M:%S',
            '%Ec': '%c',
            '%EC': '%C',
            '%Ex': '%m/%d/%y',
            '%EX': '%H:%M:%S',
            '%Ey': '%y',
            '%EY': '%Y',
            '%Od': '%d',
            '%Oe': '%e',
            '%OH': '%H',
            '%OI': '%I',
            '%Om': '%m',
            '%OM': '%M',
            '%OS': '%S',
            '%Ou': '%u',
            '%OU': '%U',
            '%OV': '%V',
            '%Ow': '%w',
            '%OW': '%W',
            '%Oy': '%y',
          });
        for (var f in p) r = r.replace(new RegExp(f, 'g'), p[f]);
        var _ = 'Sunday Monday Tuesday Wednesday Thursday Friday Saturday'.split(' '),
          C = 'January February March April May June July August September October November December'.split(' ');
        (p = {
          '%a': (d) => _[d.Ga].substring(0, 3),
          '%A': (d) => _[d.Ga],
          '%b': (d) => C[d.Sa].substring(0, 3),
          '%B': (d) => C[d.Sa],
          '%C': (d) => l(((d.Ja + 1900) / 100) | 0, 2),
          '%d': (d) => l(d.Va, 2),
          '%e': (d) => i(d.Va, 2, ' '),
          '%g': (d) => m(d).toString().substring(2),
          '%G': m,
          '%H': (d) => l(d.Ra, 2),
          '%I': (d) => ((d = d.Ra), d == 0 ? (d = 12) : 12 < d && (d -= 12), l(d, 2)),
          '%j': (d) => {
            for (var v = 0, g = 0; g <= d.Sa - 1; v += (Re(d.Ja + 1900) ? St : $t)[g++]);
            return l(d.Va + v, 3);
          },
          '%m': (d) => l(d.Sa + 1, 2),
          '%M': (d) => l(d.rb, 2),
          '%n': () => `
`,
          '%p': (d) => (0 <= d.Ra && 12 > d.Ra ? 'AM' : 'PM'),
          '%S': (d) => l(d.sb, 2),
          '%t': () => '	',
          '%u': (d) => d.Ga || 7,
          '%U': (d) => l(Math.floor((d.Ia + 7 - d.Ga) / 7), 2),
          '%V': (d) => {
            var v = Math.floor((d.Ia + 7 - ((d.Ga + 6) % 7)) / 7);
            if ((2 >= (d.Ga + 371 - d.Ia - 2) % 7 && v++, v))
              v == 53 && ((g = (d.Ga + 371 - d.Ia) % 7), g == 4 || (g == 3 && Re(d.Ja)) || (v = 1));
            else {
              v = 52;
              var g = (d.Ga + 7 - d.Ia - 1) % 7;
              (g == 4 || (g == 5 && Re((d.Ja % 400) - 1))) && v++;
            }
            return l(v, 2);
          },
          '%w': (d) => d.Ga,
          '%W': (d) => l(Math.floor((d.Ia + 7 - ((d.Ga + 6) % 7)) / 7), 2),
          '%y': (d) => (d.Ja + 1900).toString().substring(2),
          '%Y': (d) => d.Ja + 1900,
          '%z': (d) => {
            d = d.qb;
            var v = 0 <= d;
            return (d = Math.abs(d) / 60), (v ? '+' : '-') + ('0000' + ((d / 60) * 100 + (d % 60))).slice(-4);
          },
          '%Z': (d) => d.tb,
          '%%': () => '%',
        }),
          (r = r.replace(/%%/g, '\0\0'));
        for (f in p) r.includes(f) && (r = r.replace(new RegExp(f, 'g'), p[f](o)));
        return (r = r.replace(/\0\0/g, '%')), (f = vn(r)), f.length > t ? 0 : (X.set(f, e), f.length - 1);
      };
      q = a.InternalError = class extends Error {
        constructor(e) {
          super(e), (this.name = 'InternalError');
        }
      };
      for (var kt = Array(256), Se = 0; 256 > Se; ++Se) kt[Se] = String.fromCharCode(Se);
      (_t = kt),
        (y = a.BindingError =
          class extends Error {
            constructor(e) {
              super(e), (this.name = 'BindingError');
            }
          }),
        Object.assign(fe.prototype, {
          isAliasOf: function (e) {
            if (!(this instanceof fe && e instanceof fe)) return !1;
            var t = this.ma.za.xa,
              r = this.ma.ya;
            e.ma = e.ma;
            var o = e.ma.za.xa;
            for (e = e.ma.ya; t.Ca; ) (r = t.Na(r)), (t = t.Ca);
            for (; o.Ca; ) (e = o.Na(e)), (o = o.Ca);
            return t === o && r === e;
          },
          clone: function () {
            if ((this.ma.ya || Me(this), this.ma.Ma)) return (this.ma.count.value += 1), this;
            var e = W,
              t = Object,
              r = t.create,
              o = Object.getPrototypeOf(this),
              i = this.ma;
            return (
              (e = e(
                r.call(t, o, {
                  ma: { value: { count: i.count, Ka: i.Ka, Ma: i.Ma, ya: i.ya, za: i.za, Aa: i.Aa, Da: i.Da } },
                }),
              )),
              (e.ma.count.value += 1),
              (e.ma.Ka = !1),
              e
            );
          },
          delete() {
            if ((this.ma.ya || Me(this), this.ma.Ka && !this.ma.Ma))
              throw new y('Object already scheduled for deletion');
            Le(this);
            var e = this.ma;
            --e.count.value,
              e.count.value === 0 && (e.Aa ? e.Da.Fa(e.Aa) : e.za.xa.Fa(e.ya)),
              this.ma.Ma || ((this.ma.Aa = void 0), (this.ma.ya = void 0));
          },
          isDeleted: function () {
            return !this.ma.ya;
          },
          deleteLater: function () {
            if ((this.ma.ya || Me(this), this.ma.Ka && !this.ma.Ma))
              throw new y('Object already scheduled for deletion');
            return G.push(this), G.length === 1 && ie && ie(Fe), (this.ma.Ka = !0), this;
          },
        }),
        (a.getInheritedInstanceCount = () => Object.keys(te).length),
        (a.getLiveInheritedInstances = () => {
          var e = [],
            t;
          for (t in te) te.hasOwnProperty(t) && e.push(te[t]);
          return e;
        }),
        (a.flushPendingDeletes = Fe),
        (a.setDelayFunction = (e) => {
          (ie = e), G.length && ie && ie(Fe);
        }),
        Object.assign(ve.prototype, {
          eb(e) {
            return this.Za && (e = this.Za(e)), e;
          },
          Xa(e) {
            this.Fa?.(e);
          },
          argPackAdvance: 8,
          readValueFromPointer: he,
          fromWireType: function (e) {
            function t() {
              return this.Qa
                ? me(this.xa.La, { za: this.jb, ya: r, Da: this, Aa: e })
                : me(this.xa.La, { za: this, ya: e });
            }
            var r = this.eb(e);
            if (!r) return this.Xa(e), null;
            var o = Ct(this.xa, r);
            if (o !== void 0)
              return o.ma.count.value === 0
                ? ((o.ma.ya = r), (o.ma.Aa = e), o.clone())
                : ((o = o.clone()), this.Xa(e), o);
            if (((o = this.xa.cb(r)), (o = We[o]), !o)) return t.call(this);
            o = this.Pa ? o.$a : o.pointerType;
            var i = be(r, this.xa, o.xa);
            return i === null
              ? t.call(this)
              : this.Qa
              ? me(o.xa.La, { za: o, ya: i, Da: this, Aa: e })
              : me(o.xa.La, { za: o, ya: i });
          },
        }),
        (Ft = a.UnboundTypeError =
          ((e, t) => {
            var r = se(t, function (o) {
              (this.name = t),
                (this.message = o),
                (o = Error(o).stack),
                o !== void 0 &&
                  (this.stack =
                    this.toString() +
                    `
` +
                    o.replace(/^Error(:[^\n]*)?\n/, ''));
            });
            return (
              (r.prototype = Object.create(e.prototype)),
              (r.prototype.constructor = r),
              (r.prototype.toString = function () {
                return this.message === void 0 ? this.name : `${this.name}: ${this.message}`;
              }),
              r
            );
          })(Error, 'UnboundTypeError')),
        H.push(0, 1, void 0, 1, null, 1, !0, 1, !1, 1),
        (a.count_emval_handles = () => H.length / 2 - 5 - He.length);
      var gn = {
          c: (e, t, r, o) => {
            Ee(
              `Assertion failed: ${e ? Q(b, e) : ''}, at: ` +
                [t ? (t ? Q(b, t) : '') : 'unknown filename', r, o ? (o ? Q(b, o) : '') : 'unknown function'],
            );
          },
          m: (e, t, r) => {
            var o = new Gt(e);
            throw ((L[(o.ya + 16) >> 2] = 0), (L[(o.ya + 4) >> 2] = t), (L[(o.ya + 8) >> 2] = r), (yt = e), yt);
          },
          B: function () {
            return 0;
          },
          P: () => {},
          M: () => {},
          R: function () {
            return 0;
          },
          N: () => {},
          A: function () {},
          O: () => {},
          v: (e) => {
            var t = Ce[e];
            delete Ce[e];
            var r = t.Ua,
              o = t.Fa,
              i = t.Ya,
              l = i.map((h) => h.hb).concat(i.map((h) => h.nb));
            N([e], l, (h) => {
              var c = {};
              return (
                i.forEach((m, p) => {
                  var f = h[p],
                    _ = m.fb,
                    C = m.gb,
                    d = h[p + i.length],
                    v = m.mb,
                    g = m.ob;
                  c[m.bb] = {
                    read: (I) => f.fromWireType(_(C, I)),
                    write: (I, J) => {
                      var S = [];
                      v(g, I, d.toWireType(S, J)), Be(S);
                    },
                  };
                }),
                [
                  {
                    name: t.name,
                    fromWireType: (m) => {
                      var p = {},
                        f;
                      for (f in c) p[f] = c[f].read(m);
                      return o(m), p;
                    },
                    toWireType: (m, p) => {
                      for (var f in c) if (!(f in p)) throw new TypeError(`Missing field: "${f}"`);
                      var _ = r();
                      for (f in c) c[f].write(_, p[f]);
                      return m !== null && m.push(o, _), _;
                    },
                    argPackAdvance: 8,
                    readValueFromPointer: he,
                    Ea: o,
                  },
                ]
              );
            });
          },
          I: () => {},
          Y: (e, t, r, o) => {
            (t = P(t)),
              $(e, {
                name: t,
                fromWireType: function (i) {
                  return !!i;
                },
                toWireType: function (i, l) {
                  return l ? r : o;
                },
                argPackAdvance: 8,
                readValueFromPointer: function (i) {
                  return this.fromWireType(b[i]);
                },
                Ea: null,
              });
          },
          r: (e, t, r, o, i, l, h, c, m, p, f, _, C) => {
            (f = P(f)), (l = R(i, l)), c && (c = R(h, c)), p && (p = R(m, p)), (C = R(_, C));
            var d = Mt(f);
            Ie(d, function () {
              Ae(`Cannot construct ${f} due to unbound types`, [o]);
            }),
              N([e, t, r], o ? [o] : [], (v) => {
                if (((v = v[0]), o))
                  var g = v.xa,
                    I = g.La;
                else I = fe.prototype;
                v = se(f, function (...Qe) {
                  if (Object.getPrototypeOf(this) !== J) throw new y("Use 'new' to construct " + f);
                  if (S.Ha === void 0) throw new y(f + ' has no accessible constructor');
                  var Bt = S.Ha[Qe.length];
                  if (Bt === void 0)
                    throw new y(
                      `Tried to invoke ctor of ${f} with invalid number of parameters (${
                        Qe.length
                      }) - expected (${Object.keys(S.Ha).toString()}) parameters instead!`,
                    );
                  return Bt.apply(this, Qe);
                });
                var J = Object.create(I, { constructor: { value: v } });
                v.prototype = J;
                var S = new Lt(f, v, J, C, g, l, c, p);
                if (S.Ca) {
                  var ye;
                  (ye = S.Ca).Wa ?? (ye.Wa = []), S.Ca.Wa.push(S);
                }
                return (
                  (g = new ve(f, S, !0, !1, !1)),
                  (ye = new ve(f + '*', S, !1, !1, !1)),
                  (I = new ve(f + ' const*', S, !1, !0, !1)),
                  (We[e] = { pointerType: ye, $a: I }),
                  bt(d, v),
                  [g, ye, I]
                );
              });
          },
          q: (e, t, r, o, i, l) => {
            var h = je(t, r);
            (i = R(o, i)),
              N([], [e], (c) => {
                c = c[0];
                var m = `constructor ${c.name}`;
                if ((c.xa.Ha === void 0 && (c.xa.Ha = []), c.xa.Ha[t - 1] !== void 0))
                  throw new y(
                    `Cannot register multiple constructors with identical number of parameters (${t - 1}) for class '${
                      c.name
                    }'! Overload resolution is currently only performed using the parameter count, not actual type info!`,
                  );
                return (
                  (c.xa.Ha[t - 1] = () => {
                    Ae(`Cannot construct ${c.name} due to unbound types`, h);
                  }),
                  N([], h, (p) => (p.splice(1, 0, null), (c.xa.Ha[t - 1] = Ue(m, p, null, i, l)), [])),
                  []
                );
              });
          },
          f: (e, t, r, o, i, l, h, c) => {
            var m = je(r, o);
            (t = P(t)),
              (t = It(t)),
              (l = R(i, l)),
              N([], [e], (p) => {
                function f() {
                  Ae(`Cannot call ${_} due to unbound types`, m);
                }
                p = p[0];
                var _ = `${p.name}.${t}`;
                t.startsWith('@@') && (t = Symbol[t.substring(2)]), c && p.xa.kb.push(t);
                var C = p.xa.La,
                  d = C[t];
                return (
                  d === void 0 || (d.Ba === void 0 && d.className !== p.name && d.Oa === r - 2)
                    ? ((f.Oa = r - 2), (f.className = p.name), (C[t] = f))
                    : (xe(C, t, _), (C[t].Ba[r - 2] = f)),
                  N(
                    [],
                    m,
                    (v) => (
                      (v = Ue(_, v, p, l, h)),
                      C[t].Ba === void 0 ? ((v.Oa = r - 2), (C[t] = v)) : (C[t].Ba[r - 2] = v),
                      []
                    ),
                  ),
                  []
                );
              });
          },
          X: (e) => $(e, Pt),
          x: (e, t, r, o) => {
            function i() {}
            (t = P(t)),
              (i.values = {}),
              $(e, {
                name: t,
                constructor: i,
                fromWireType: function (l) {
                  return this.constructor.values[l];
                },
                toWireType: (l, h) => h.value,
                argPackAdvance: 8,
                readValueFromPointer: tn(t, r, o),
                Ea: null,
              }),
              Ie(t, i);
          },
          k: (e, t, r) => {
            var o = Ne(e, 'enum');
            (t = P(t)),
              (e = o.constructor),
              (o = Object.create(o.constructor.prototype, {
                value: { value: r },
                constructor: { value: se(`${o.name}_${t}`, function () {}) },
              })),
              (e.values[r] = o),
              (e[t] = o);
          },
          C: (e, t, r) => {
            (t = P(t)),
              $(e, {
                name: t,
                fromWireType: (o) => o,
                toWireType: (o, i) => i,
                argPackAdvance: 8,
                readValueFromPointer: nn(t, r),
                Ea: null,
              });
          },
          E: (e, t, r, o, i, l) => {
            var h = je(t, r);
            (e = P(e)),
              (e = It(e)),
              (i = R(o, i)),
              Ie(
                e,
                function () {
                  Ae(`Cannot call ${e} due to unbound types`, h);
                },
                t - 1,
              ),
              N([], h, (c) => (bt(e, Ue(e, [c[0], null].concat(c.slice(1)), null, i, l), t - 1), []));
          },
          l: (e, t, r, o, i) => {
            if (((t = P(t)), i === -1 && (i = 4294967295), (i = (c) => c), o === 0)) {
              var l = 32 - 8 * r;
              i = (c) => (c << l) >>> l;
            }
            var h = t.includes('unsigned')
              ? function (c, m) {
                  return m >>> 0;
                }
              : function (c, m) {
                  return m;
                };
            $(e, {
              name: t,
              fromWireType: i,
              toWireType: h,
              argPackAdvance: 8,
              readValueFromPointer: rn(t, r, o !== 0),
              Ea: null,
            });
          },
          g: (e, t, r) => {
            function o(l) {
              return new i(X.buffer, L[(l + 4) >> 2], L[l >> 2]);
            }
            var i = [
              Int8Array,
              Uint8Array,
              Int16Array,
              Uint16Array,
              Int32Array,
              Uint32Array,
              Float32Array,
              Float64Array,
            ][t];
            (r = P(r)), $(e, { name: r, fromWireType: o, argPackAdvance: 8, readValueFromPointer: o }, { ib: !0 });
          },
          w: (e) => {
            $(e, Pt);
          },
          ca: (e, t, r, o, i, l, h, c, m, p, f, _) => {
            (r = P(r)),
              (l = R(i, l)),
              (c = R(h, c)),
              (p = R(m, p)),
              (_ = R(f, _)),
              N([e], [t], (C) => ((C = C[0]), [new ve(r, C.xa, !1, !1, !0, C, o, l, c, p, _)]));
          },
          D: (e, t) => {
            t = P(t);
            var r = t === 'std::string';
            $(e, {
              name: t,
              fromWireType: function (o) {
                var i = L[o >> 2],
                  l = o + 4;
                if (r)
                  for (var h = l, c = 0; c <= i; ++c) {
                    var m = l + c;
                    if (c == i || b[m] == 0) {
                      if (((h = h ? Q(b, h, m - h) : ''), p === void 0)) var p = h;
                      else (p += '\0'), (p += h);
                      h = m + 1;
                    }
                  }
                else {
                  for (p = Array(i), c = 0; c < i; ++c) p[c] = String.fromCharCode(b[l + c]);
                  p = p.join('');
                }
                return V(o), p;
              },
              toWireType: function (o, i) {
                i instanceof ArrayBuffer && (i = new Uint8Array(i));
                var l = typeof i == 'string';
                if (!(l || i instanceof Uint8Array || i instanceof Uint8ClampedArray || i instanceof Int8Array))
                  throw new y('Cannot pass non-string to std::string');
                var h = r && l ? gt(i) : i.length,
                  c = Ze(4 + h + 1),
                  m = c + 4;
                if (((L[c >> 2] = h), r && l)) wt(i, b, m, h + 1);
                else if (l)
                  for (l = 0; l < h; ++l) {
                    var p = i.charCodeAt(l);
                    if (255 < p) throw (V(m), new y('String has UTF-16 code units that do not fit in 8 bits'));
                    b[m + l] = p;
                  }
                else for (l = 0; l < h; ++l) b[m + l] = i[l];
                return o !== null && o.push(V, c), c;
              },
              argPackAdvance: 8,
              readValueFromPointer: he,
              Ea(o) {
                V(o);
              },
            });
          },
          u: (e, t, r) => {
            if (((r = P(r)), t === 2))
              var o = an,
                i = on,
                l = sn,
                h = (c) => de[c >> 1];
            else t === 4 && ((o = ln), (i = un), (l = dn), (h = (c) => L[c >> 2]));
            $(e, {
              name: r,
              fromWireType: (c) => {
                for (var m = L[c >> 2], p, f = c + 4, _ = 0; _ <= m; ++_) {
                  var C = c + 4 + _ * t;
                  (_ == m || h(C) == 0) &&
                    ((f = o(f, C - f)), p === void 0 ? (p = f) : ((p += '\0'), (p += f)), (f = C + t));
                }
                return V(c), p;
              },
              toWireType: (c, m) => {
                if (typeof m != 'string') throw new y(`Cannot pass non-string to C++ string type ${r}`);
                var p = l(m),
                  f = Ze(4 + p + t);
                return (L[f >> 2] = p / t), i(m, f + 4, p + t), c !== null && c.push(V, f), f;
              },
              argPackAdvance: 8,
              readValueFromPointer: he,
              Ea(c) {
                V(c);
              },
            });
          },
          s: (e, t, r, o, i, l) => {
            Ce[e] = { name: P(t), Ua: R(r, o), Fa: R(i, l), Ya: [] };
          },
          j: (e, t, r, o, i, l, h, c, m, p) => {
            Ce[e].Ya.push({ bb: P(t), hb: r, fb: R(o, i), gb: l, nb: h, mb: R(c, m), ob: p });
          },
          Z: (e, t) => {
            (t = P(t)), $(e, { ub: !0, name: t, argPackAdvance: 0, fromWireType: () => {}, toWireType: () => {} });
          },
          J: () => {
            throw 1 / 0;
          },
          aa: (e, t, r, o) => ((e = Je[e]), (t = Ye(t)), e(null, t, r, o)),
          F: Ve,
          $: (e, t, r) => {
            var o = hn(e, t),
              i = o.shift();
            e--;
            var l = Array(e);
            return (
              (t = `methodCaller<(${o.map((h) => h.name).join(', ')}) => ${i.name}>`),
              cn(
                se(t, (h, c, m, p) => {
                  for (var f = 0, _ = 0; _ < e; ++_)
                    (l[_] = o[_].readValueFromPointer(p + f)), (f += o[_].argPackAdvance);
                  return (
                    (c = r === 1 ? pn(c, l) : c.apply(h, l)),
                    (h = []),
                    (c = i.toWireType(h, c)),
                    h.length && (L[m >> 2] = Te(h)),
                    c
                  );
                }),
              )
            );
          },
          ba: (e) => {
            9 < e && (H[e + 1] += 1);
          },
          _: (e) => {
            var t = Ye(e);
            Be(t), Ve(e);
          },
          o: (e, t) => ((e = Ne(e, '_emval_take_value')), (e = e.readValueFromPointer(t)), Te(e)),
          W: () => {
            Ee('');
          },
          V: () => performance.now(),
          L: (e) => {
            var t = b.length;
            if (((e >>>= 0), 2147483648 < e)) return !1;
            for (var r = 1; 4 >= r; r *= 2) {
              var o = t * (1 + 0.2 / r);
              o = Math.min(o, e + 100663296);
              var i = Math;
              o = Math.max(e, o);
              e: {
                i =
                  (i.min.call(i, 2147483648, o + ((65536 - (o % 65536)) % 65536)) - _e.buffer.byteLength + 65535) /
                  65536;
                try {
                  _e.grow(i), lt();
                  var l = 1;
                  break e;
                } catch {}
                l = void 0;
              }
              if (l) return !0;
            }
            return !1;
          },
          S: (e, t) => {
            var r = 0;
            return (
              Tt().forEach((o, i) => {
                var l = t + r;
                for (i = L[(e + 4 * i) >> 2] = l, l = 0; l < o.length; ++l) X[i++] = o.charCodeAt(l);
                (X[i] = 0), (r += o.length + 1);
              }),
              0
            );
          },
          T: (e, t) => {
            var r = Tt();
            L[e >> 2] = r.length;
            var o = 0;
            return r.forEach((i) => (o += i.length + 1)), (L[t >> 2] = o), 0;
          },
          t: () => 52,
          z: () => 52,
          H: function () {
            return 70;
          },
          Q: (e, t, r, o) => {
            for (var i = 0, l = 0; l < r; l++) {
              var h = L[t >> 2],
                c = L[(t + 4) >> 2];
              t += 8;
              for (var m = 0; m < c; m++) {
                var p = b[h + m],
                  f = mn[e];
                p === 0 || p === 10 ? ((e === 1 ? Ht : re)(Q(f, 0)), (f.length = 0)) : f.push(p);
              }
              i += c;
            }
            return (L[o >> 2] = i), 0;
          },
          U: (e, t) => (Rt(b.subarray(e, e + t)), 0),
          i: Mn,
          d: Cn,
          e: En,
          p: Ln,
          y: xn,
          b: wn,
          a: _n,
          h: Fn,
          n: bn,
          G: In,
          K: (e, t, r, o) => yn(e, t, r, o),
        },
        F = (function () {
          function e(r) {
            return (
              (F = r.exports),
              (_e = F.da),
              lt(),
              (k = F.ha),
              dt.unshift(F.ea),
              Z--,
              a.monitorRunDependencies?.(Z),
              Z == 0 && ce && ((r = ce), (ce = null), r()),
              F
            );
          }
          var t = { a: gn };
          if ((Z++, a.monitorRunDependencies?.(Z), a.instantiateWasm))
            try {
              return a.instantiateWasm(t, e);
            } catch (r) {
              re(`Module.instantiateWasm callback failed with error: ${r}`), w(r);
            }
          return (
            Nt(t, function (r) {
              e(r.instance);
            }).catch(w),
            {}
          );
        })(),
        Ze = (e) => (Ze = F.fa)(e),
        Dt = (e) => (Dt = F.ga)(e),
        V = (e) => (V = F.ia)(e),
        D = (e, t) => (D = F.ja)(e, t),
        z = (e) => (z = F.ka)(e),
        O = () => (O = F.la)();
      (a.dynCall_iijj = (e, t, r, o, i, l) => (a.dynCall_iijj = F.na)(e, t, r, o, i, l)),
        (a.dynCall_vijj = (e, t, r, o, i, l) => (a.dynCall_vijj = F.oa)(e, t, r, o, i, l)),
        (a.dynCall_jiii = (e, t, r, o) => (a.dynCall_jiii = F.pa)(e, t, r, o)),
        (a.dynCall_jii = (e, t, r) => (a.dynCall_jii = F.qa)(e, t, r));
      var zt = (a.dynCall_viiij = (e, t, r, o, i, l) => (zt = a.dynCall_viiij = F.ra)(e, t, r, o, i, l));
      (a.dynCall_jiji = (e, t, r, o, i) => (a.dynCall_jiji = F.sa)(e, t, r, o, i)),
        (a.dynCall_viijii = (e, t, r, o, i, l, h) => (a.dynCall_viijii = F.ta)(e, t, r, o, i, l, h)),
        (a.dynCall_iiiiij = (e, t, r, o, i, l, h) => (a.dynCall_iiiiij = F.ua)(e, t, r, o, i, l, h)),
        (a.dynCall_iiiiijj = (e, t, r, o, i, l, h, c, m) => (a.dynCall_iiiiijj = F.va)(e, t, r, o, i, l, h, c, m)),
        (a.dynCall_iiiiiijj = (e, t, r, o, i, l, h, c, m, p) =>
          (a.dynCall_iiiiiijj = F.wa)(e, t, r, o, i, l, h, c, m, p));
      function wn(e, t) {
        var r = O();
        try {
          k.get(e)(t);
        } catch (o) {
          if ((z(r), o !== o + 0)) throw o;
          D(1, 0);
        }
      }
      function _n(e, t, r) {
        var o = O();
        try {
          k.get(e)(t, r);
        } catch (i) {
          if ((z(o), i !== i + 0)) throw i;
          D(1, 0);
        }
      }
      function En(e, t, r, o) {
        var i = O();
        try {
          return k.get(e)(t, r, o);
        } catch (l) {
          if ((z(i), l !== l + 0)) throw l;
          D(1, 0);
        }
      }
      function Cn(e, t, r) {
        var o = O();
        try {
          return k.get(e)(t, r);
        } catch (i) {
          if ((z(o), i !== i + 0)) throw i;
          D(1, 0);
        }
      }
      function Mn(e, t) {
        var r = O();
        try {
          return k.get(e)(t);
        } catch (o) {
          if ((z(r), o !== o + 0)) throw o;
          D(1, 0);
        }
      }
      function Ln(e, t, r, o, i, l) {
        var h = O();
        try {
          return k.get(e)(t, r, o, i, l);
        } catch (c) {
          if ((z(h), c !== c + 0)) throw c;
          D(1, 0);
        }
      }
      function bn(e, t, r, o, i) {
        var l = O();
        try {
          k.get(e)(t, r, o, i);
        } catch (h) {
          if ((z(l), h !== h + 0)) throw h;
          D(1, 0);
        }
      }
      function Fn(e, t, r, o) {
        var i = O();
        try {
          k.get(e)(t, r, o);
        } catch (l) {
          if ((z(i), l !== l + 0)) throw l;
          D(1, 0);
        }
      }
      function xn(e) {
        var t = O();
        try {
          k.get(e)();
        } catch (r) {
          if ((z(t), r !== r + 0)) throw r;
          D(1, 0);
        }
      }
      function In(e, t, r, o, i, l) {
        var h = O();
        try {
          zt(e, t, r, o, i, l);
        } catch (c) {
          if ((z(h), c !== c + 0)) throw c;
          D(1, 0);
        }
      }
      var $e;
      ce = function e() {
        $e || Ot(), $e || (ce = e);
      };
      function Ot() {
        function e() {
          if (!$e && (($e = !0), (a.calledRun = !0), !ot)) {
            if ((Oe(dt), u(a), a.onRuntimeInitialized && a.onRuntimeInitialized(), a.postRun))
              for (typeof a.postRun == 'function' && (a.postRun = [a.postRun]); a.postRun.length; ) {
                var t = a.postRun.shift();
                ct.unshift(t);
              }
            Oe(ct);
          }
        }
        if (!(0 < Z)) {
          if (a.preRun) for (typeof a.preRun == 'function' && (a.preRun = [a.preRun]); a.preRun.length; ) Vt();
          Oe(ut),
            0 < Z ||
              (a.setStatus
                ? (a.setStatus('Running...'),
                  setTimeout(function () {
                    setTimeout(function () {
                      a.setStatus('');
                    }, 1),
                      e();
                  }, 1))
                : e());
        }
      }
      if (a.preInit)
        for (typeof a.preInit == 'function' && (a.preInit = [a.preInit]); 0 < a.preInit.length; ) a.preInit.pop()();
      return Ot(), T;
    };
  })(),
  Wt = Rn;
var ne = class {
  constructor() {
    throw new Error('RendererLoader is a static class and cannot be instantiated.');
  }
  static async _tryLoad(n) {
    return await Wt({ locateFile: () => n });
  }
  static async _loadWithBackup() {
    return (
      this._ModulePromise ||
        (this._ModulePromise = this._tryLoad(this._wasmURL).catch(async (n) => {
          let a = `https://unpkg.com/${ge.name}@${ge.version}/dist/dotlottie-player.wasm`;
          console.warn(`Primary WASM load failed from ${this._wasmURL}. Error: ${n.message}`),
            console.warn(`Attempting to load WASM from backup URL: ${a}`);
          try {
            return await this._tryLoad(a);
          } catch (u) {
            throw (
              (console.error(`Primary WASM URL failed: ${n.message}`),
              console.error(`Backup WASM URL failed: ${u.message}`),
              new Error('WASM loading failed from all sources.'))
            );
          }
        })),
      this._ModulePromise
    );
  }
  static async load() {
    return this._loadWithBackup();
  }
  static setWasmUrl(n) {
    (this._wasmURL = n), (this._ModulePromise = null);
  }
};
x(ne, '_ModulePromise', null),
  x(ne, '_wasmURL', `https://cdn.jsdelivr.net/npm/${ge.name}@${ge.version}/dist/dotlottie-player.wasm`);
var De = class {
  constructor() {
    x(this, '_eventListeners', new Map());
  }
  addEventListener(n, a) {
    let u = this._eventListeners.get(n);
    u || ((u = new Set()), this._eventListeners.set(n, u)), u.add(a);
  }
  removeEventListener(n, a) {
    let u = this._eventListeners.get(n);
    u && (a ? (u.delete(a), u.size === 0 && this._eventListeners.delete(n)) : this._eventListeners.delete(n));
  }
  dispatch(n) {
    this._eventListeners.get(n.type)?.forEach((u) => u(n));
  }
  removeAllEventListeners() {
    this._eventListeners.clear();
  }
};
function Sn(s) {
  return /^#([\da-f]{6}|[\da-f]{8})$/iu.test(s);
}
function jt(s) {
  if (!Sn(s)) return 0;
  let n = s.replace('#', '');
  return (n = n.length === 6 ? `${n}ff` : n), parseInt(n, 16);
}
var tt = (s, n) =>
    s === 'reverse'
      ? n.Mode.Reverse
      : s === 'bounce'
      ? n.Mode.Bounce
      : s === 'reverse-bounce'
      ? n.Mode.ReverseBounce
      : n.Mode.Forward,
  nt = (s, n) =>
    s === 'contain'
      ? n.Fit.Contain
      : s === 'cover'
      ? n.Fit.Cover
      : s === 'fill'
      ? n.Fit.Fill
      : s === 'fit-height'
      ? n.Fit.FitHeight
      : s === 'fit-width'
      ? n.Fit.FitWidth
      : n.Fit.None,
  rt = (s, n) => {
    let a = new n.VectorFloat();
    return a.push_back(s[0]), a.push_back(s[1]), a;
  },
  at = (s, n) => {
    let a = new n.VectorFloat();
    return s.length !== 2 || (a.push_back(s[0]), a.push_back(s[1])), a;
  },
  M = class M {
    constructor(n) {
      x(this, '_canvas');
      x(this, '_context', null);
      x(this, '_eventManager');
      x(this, '_animationFrameId', null);
      x(this, '_frameManager');
      x(this, '_dotLottieCore', null);
      x(this, '_renderConfig', {});
      x(this, '_isFrozen', !1);
      x(this, '_backgroundColor', null);
      (this._canvas = n.canvas),
        (this._context = this._canvas.getContext('2d')),
        (this._eventManager = new De()),
        (this._frameManager = new ke()),
        (this._renderConfig = n.renderConfig ?? {}),
        ne
          .load()
          .then((a) => {
            (M._wasmModule = a),
              (this._dotLottieCore = new a.DotLottiePlayer({
                autoplay: n.autoplay ?? !1,
                backgroundColor: 0,
                loopAnimation: n.loop ?? !1,
                mode: tt(n.mode ?? 'forward', a),
                segment: at(n.segment ?? [], a),
                speed: n.speed ?? 1,
                useFrameInterpolation: n.useFrameInterpolation ?? !0,
                marker: n.marker ?? '',
                layout: n.layout ? { align: rt(n.layout.align, a), fit: nt(n.layout.fit, a) } : a.createDefaultLayout(),
              })),
              this._eventManager.dispatch({ type: 'ready' }),
              n.data ? this._loadFromData(n.data) : n.src && this._loadFromSrc(n.src),
              n.backgroundColor && this.setBackgroundColor(n.backgroundColor);
          })
          .catch((a) => {
            this._eventManager.dispatch({ type: 'loadError', error: new Error(`Failed to load wasm module: ${a}`) });
          });
    }
    _loadFromSrc(n) {
      async function a() {
        let u = await fetch(n);
        if (!u.ok) throw new Error(`Failed to fetch the animation data from URL: ${n}. ${u.status}: ${u.statusText}`);
        let w = (u.headers.get('content-type') ?? '').trim(),
          T;
        return (
          ['application/json', 'text/plain'].some((B) => w.startsWith(B))
            ? (T = await u.text())
            : (T = await u.arrayBuffer()),
          T
        );
      }
      a()
        .then((u) => {
          this._loadFromData(u);
        })
        .catch((u) => {
          this._eventManager.dispatch({
            type: 'loadError',
            error: new Error(`Failed to load animation data from URL: ${n}. ${u}`),
          });
        });
    }
    _loadFromData(n) {
      if (this._dotLottieCore === null) return;
      let a = this._canvas.width,
        u = this._canvas.height,
        w = !1;
      if (typeof n == 'string') w = this._dotLottieCore.loadAnimationData(n, a, u);
      else if (n instanceof ArrayBuffer) w = this._dotLottieCore.loadDotLottieData(n, a, u);
      else if (typeof n == 'object') w = this._dotLottieCore.loadAnimationData(JSON.stringify(n), a, u);
      else {
        this._eventManager.dispatch({
          type: 'loadError',
          error: new Error('Unsupported data type for animation data. Expected a string or ArrayBuffer.'),
        });
        return;
      }
      w
        ? (this._eventManager.dispatch({ type: 'load' }),
          le && this.resize(),
          this._eventManager.dispatch({ type: 'frame', currentFrame: this._dotLottieCore.currentFrame() }),
          this._render(),
          this._dotLottieCore.config().autoplay &&
            (this._dotLottieCore.play(),
            this._dotLottieCore.isPlaying()
              ? (this._eventManager.dispatch({ type: 'play' }),
                (this._animationFrameId = this._frameManager.requestAnimationFrame(this._draw.bind(this))))
              : console.error('something went wrong, the animation was suppose to autoplay')))
        : this._eventManager.dispatch({ type: 'loadError', error: new Error('Failed to load animation data') });
    }
    get activeAnimationId() {
      return this._dotLottieCore?.activeAnimationId();
    }
    get activeThemeId() {
      return this._dotLottieCore?.activeThemeId();
    }
    get layout() {
      let n = this._dotLottieCore?.config().layout;
      if (n)
        return {
          align: [n.align.get(0), n.align.get(1)],
          fit: (() => {
            switch (n.fit) {
              case M._wasmModule?.Fit.Contain:
                return 'contain';
              case M._wasmModule?.Fit.Cover:
                return 'cover';
              case M._wasmModule?.Fit.Fill:
                return 'fill';
              case M._wasmModule?.Fit.FitHeight:
                return 'fit-height';
              case M._wasmModule?.Fit.FitWidth:
                return 'fit-width';
              case M._wasmModule?.Fit.None:
                return 'none';
              default:
                return 'contain';
            }
          })(),
        };
    }
    get marker() {
      return this._dotLottieCore?.config().marker;
    }
    get manifest() {
      try {
        let n = this._dotLottieCore?.manifestString();
        if (this._dotLottieCore === null || !n) return null;
        let a = JSON.parse(n);
        return Object.keys(a).length === 0 ? null : a;
      } catch {
        return null;
      }
    }
    get renderConfig() {
      return this._renderConfig;
    }
    get segment() {
      let n = this._dotLottieCore?.config().segment;
      if (n && n.size() === 2) return [n.get(0), n.get(1)];
    }
    get loop() {
      return this._dotLottieCore?.config().loopAnimation ?? !1;
    }
    get mode() {
      let n = this._dotLottieCore?.config().mode;
      return n === M._wasmModule?.Mode.Reverse
        ? 'reverse'
        : n === M._wasmModule?.Mode.Bounce
        ? 'bounce'
        : n === M._wasmModule?.Mode.ReverseBounce
        ? 'reverse-bounce'
        : 'forward';
    }
    get isFrozen() {
      return this._isFrozen;
    }
    get backgroundColor() {
      return this._backgroundColor ?? '';
    }
    get autoplay() {
      return this._dotLottieCore?.config().autoplay ?? !1;
    }
    get useFrameInterpolation() {
      return this._dotLottieCore?.config().useFrameInterpolation ?? !1;
    }
    get speed() {
      return this._dotLottieCore?.config().speed ?? 0;
    }
    get isReady() {
      return this._dotLottieCore !== null;
    }
    get isLoaded() {
      return this._dotLottieCore?.isLoaded() ?? !1;
    }
    get isPlaying() {
      return this._dotLottieCore?.isPlaying() ?? !1;
    }
    get isPaused() {
      return this._dotLottieCore?.isPaused() ?? !1;
    }
    get isStopped() {
      return this._dotLottieCore?.isStopped() ?? !1;
    }
    get currentFrame() {
      return this._dotLottieCore?.currentFrame() ?? 0;
    }
    get loopCount() {
      return this._dotLottieCore?.loopCount() ?? 0;
    }
    get totalFrames() {
      return this._dotLottieCore?.totalFrames() ?? 0;
    }
    get duration() {
      return this._dotLottieCore?.duration() ?? 0;
    }
    get segmentDuration() {
      return this._dotLottieCore?.segmentDuration() ?? 0;
    }
    get canvas() {
      return this._canvas;
    }
    load(n) {
      this._dotLottieCore === null ||
        M._wasmModule === null ||
        (this._dotLottieCore.setConfig({
          autoplay: n.autoplay ?? !1,
          backgroundColor: 0,
          loopAnimation: n.loop ?? !1,
          mode: tt(n.mode ?? 'forward', M._wasmModule),
          segment: at(n.segment ?? [], M._wasmModule),
          speed: n.speed ?? 1,
          useFrameInterpolation: n.useFrameInterpolation ?? !0,
          marker: n.marker ?? '',
          layout: n.layout
            ? { align: rt(n.layout.align, M._wasmModule), fit: nt(n.layout.fit, M._wasmModule) }
            : M._wasmModule.createDefaultLayout(),
        }),
        n.data ? this._loadFromData(n.data) : n.src && this._loadFromSrc(n.src),
        this.setBackgroundColor(n.backgroundColor ?? ''));
    }
    _render() {
      if (this._dotLottieCore === null || this._context === null) return !1;
      if (this._dotLottieCore.render()) {
        let a = this._dotLottieCore.buffer(),
          u = new Uint8ClampedArray(a, 0, this._canvas.width * this._canvas.height * 4),
          w = null;
        return (
          typeof ImageData > 'u'
            ? ((w = this._context.createImageData(this._canvas.width, this._canvas.height)), w.data.set(u))
            : (w = new ImageData(u, this._canvas.width, this._canvas.height)),
          this._context.putImageData(w, 0, 0),
          this._eventManager.dispatch({ type: 'render', currentFrame: this._dotLottieCore.currentFrame() }),
          !0
        );
      }
      return !1;
    }
    _draw() {
      if (this._dotLottieCore === null || this._context === null || !this._dotLottieCore.isPlaying()) return;
      let n = this._dotLottieCore.requestFrame();
      this._dotLottieCore.setFrame(n) &&
        (this._eventManager.dispatch({ type: 'frame', currentFrame: this._dotLottieCore.currentFrame() }),
        this._render() &&
          this._dotLottieCore.isComplete() &&
          (this._dotLottieCore.config().loopAnimation
            ? this._eventManager.dispatch({ type: 'loop', loopCount: this._dotLottieCore.loopCount() })
            : this._eventManager.dispatch({ type: 'complete' }))),
        (this._animationFrameId = this._frameManager.requestAnimationFrame(this._draw.bind(this)));
    }
    play() {
      if (this._dotLottieCore === null) return;
      let n = this._dotLottieCore.play();
      (this._isFrozen = !1),
        n &&
          (this._eventManager.dispatch({ type: 'play' }),
          (this._animationFrameId = this._frameManager.requestAnimationFrame(this._draw.bind(this))));
    }
    pause() {
      if (this._dotLottieCore === null) return;
      this._dotLottieCore.pause() && this._eventManager.dispatch({ type: 'pause' });
    }
    stop() {
      if (this._dotLottieCore === null) return;
      this._dotLottieCore.stop() &&
        (this._eventManager.dispatch({ type: 'frame', currentFrame: this._dotLottieCore.currentFrame() }),
        this._render(),
        this._eventManager.dispatch({ type: 'stop' }));
    }
    setFrame(n) {
      if (this._dotLottieCore === null || n < 0 || n > this._dotLottieCore.totalFrames()) return;
      this._dotLottieCore.seek(n) &&
        (this._eventManager.dispatch({ type: 'frame', currentFrame: this._dotLottieCore.currentFrame() }),
        this._render());
    }
    setSpeed(n) {
      this._dotLottieCore !== null && this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), speed: n });
    }
    setBackgroundColor(n) {
      this._dotLottieCore !== null &&
        (le && this._canvas instanceof HTMLCanvasElement
          ? (this._canvas.style.backgroundColor = n)
          : this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), backgroundColor: jt(n) }),
        (this._backgroundColor = n));
    }
    setLoop(n) {
      this._dotLottieCore !== null &&
        this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), loopAnimation: n });
    }
    setUseFrameInterpolation(n) {
      this._dotLottieCore !== null &&
        this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), useFrameInterpolation: n });
    }
    addEventListener(n, a) {
      this._eventManager.addEventListener(n, a);
    }
    removeEventListener(n, a) {
      this._eventManager.removeEventListener(n, a);
    }
    destroy() {
      this._dotLottieCore?.delete(),
        (this._dotLottieCore = null),
        (this._context = null),
        this._eventManager.dispatch({ type: 'destroy' }),
        this._eventManager.removeAllEventListeners(),
        this._cleanupStateMachineListeners();
    }
    freeze() {
      this._animationFrameId !== null &&
        (this._frameManager.cancelAnimationFrame(this._animationFrameId),
        (this._animationFrameId = null),
        (this._isFrozen = !0),
        this._eventManager.dispatch({ type: 'freeze' }));
    }
    unfreeze() {
      this._animationFrameId === null &&
        ((this._animationFrameId = this._frameManager.requestAnimationFrame(this._draw.bind(this))),
        (this._isFrozen = !1),
        this._eventManager.dispatch({ type: 'unfreeze' }));
    }
    resize() {
      if (le && this._canvas instanceof HTMLCanvasElement) {
        let a = this._renderConfig.devicePixelRatio || window.devicePixelRatio || 1,
          { height: u, width: w } = this._canvas.getBoundingClientRect();
        (this._canvas.width = w * a), (this._canvas.height = u * a);
      }
      this._dotLottieCore?.resize(this._canvas.width, this._canvas.height) && this._render();
    }
    setSegment(n, a) {
      this._dotLottieCore === null ||
        M._wasmModule === null ||
        this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), segment: at([n, a], M._wasmModule) });
    }
    setMode(n) {
      this._dotLottieCore === null ||
        M._wasmModule === null ||
        this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), mode: tt(n, M._wasmModule) });
    }
    setRenderConfig(n) {
      this._renderConfig = n;
    }
    loadAnimation(n) {
      if (this._dotLottieCore === null || this._dotLottieCore.activeAnimationId() === n) return;
      this._dotLottieCore.loadAnimation(n, this._canvas.width, this._canvas.height)
        ? (this._eventManager.dispatch({ type: 'load' }), this.resize())
        : this._eventManager.dispatch({ type: 'loadError', error: new Error(`Failed to animation :${n}`) });
    }
    setMarker(n) {
      this._dotLottieCore !== null && this._dotLottieCore.setConfig({ ...this._dotLottieCore.config(), marker: n });
    }
    markers() {
      let n = this._dotLottieCore?.markers();
      if (n) {
        let a = [];
        for (let u = 0; u < n.size(); u += 1) {
          let w = n.get(u);
          a.push({ name: w.name, time: w.time, duration: w.duration });
        }
        return a;
      }
      return [];
    }
    loadTheme(n) {
      if (this._dotLottieCore === null) return !1;
      let a = this._dotLottieCore.loadTheme(n);
      return this._render(), a;
    }
    loadThemeData(n) {
      if (this._dotLottieCore === null) return !1;
      let a = this._dotLottieCore.loadThemeData(n);
      return this._render(), a;
    }
    setLayout(n) {
      this._dotLottieCore === null ||
        M._wasmModule === null ||
        this._dotLottieCore.setConfig({
          ...this._dotLottieCore.config(),
          layout: { align: rt(n.align, M._wasmModule), fit: nt(n.fit, M._wasmModule) },
        });
    }
    setViewport(n, a, u, w) {
      return this._dotLottieCore === null ? !1 : this._dotLottieCore.setViewport(n, a, u, w);
    }
    static setWasmUrl(n) {
      ne.setWasmUrl(n);
    }
    loadStateMachine(n) {
      return this._dotLottieCore?.loadStateMachine(n) ?? !1;
    }
    startStateMachine() {
      let n = this._dotLottieCore?.startStateMachine() ?? !1;
      return n && this._setupStateMachineListeners(), n;
    }
    stopStateMachine() {
      let n = this._dotLottieCore?.stopStateMachine() ?? !1;
      return n && this._cleanupStateMachineListeners(), n;
    }
    _getPointerPosition(n) {
      let a = this._canvas.getBoundingClientRect(),
        u = this._canvas.width / a.width,
        w = this._canvas.height / a.height,
        T = this._renderConfig.devicePixelRatio || window.devicePixelRatio || 1,
        B = ((n.clientX - a.left) * u) / T,
        K = ((n.clientY - a.top) * w) / T;
      return { x: B, y: K };
    }
    _onPointerUp(n) {
      let { x: a, y: u } = this._getPointerPosition(n);
      this.postStateMachineEvent(`OnPointerUp: ${a} ${u}`);
    }
    _onPointerDown(n) {
      let { x: a, y: u } = this._getPointerPosition(n);
      this.postStateMachineEvent(`OnPointerDown: ${a} ${u}`);
    }
    _onPointerMove(n) {
      let { x: a, y: u } = this._getPointerPosition(n);
      this.postStateMachineEvent(`OnPointerMove: ${a} ${u}`);
    }
    _onPointerEnter(n) {
      let { x: a, y: u } = this._getPointerPosition(n);
      this.postStateMachineEvent(`OnPointerEnter: ${a} ${u}`);
    }
    _onPointerLeave(n) {
      let { x: a, y: u } = this._getPointerPosition(n);
      this.postStateMachineEvent(`OnPointerExit: ${a} ${u}`);
    }
    _onComplete() {
      this.postStateMachineEvent('OnComplete');
    }
    postStateMachineEvent(n) {
      return this._dotLottieCore?.postEventPayload(n) ?? !1;
    }
    getStateMachineListeners() {
      if (!this._dotLottieCore) return [];
      let n = this._dotLottieCore.stateMachineFrameworkSetup(),
        a = [];
      for (let u = 0; u < n.size(); u += 1) a.push(n.get(u));
      return a;
    }
    _setupStateMachineListeners() {
      if (le && this._canvas instanceof HTMLCanvasElement && this._dotLottieCore !== null && this.isLoaded) {
        let n = this.getStateMachineListeners();
        n.includes('PointerUp') && this._canvas.addEventListener('pointerup', this._onPointerUp.bind(this)),
          n.includes('PointerDown') && this._canvas.addEventListener('pointerdown', this._onPointerDown.bind(this)),
          n.includes('PointerMove') && this._canvas.addEventListener('pointermove', this._onPointerMove.bind(this)),
          n.includes('PointerEnter') && this._canvas.addEventListener('pointerenter', this._onPointerEnter.bind(this)),
          n.includes('PointerExit') && this._canvas.addEventListener('pointerleave', this._onPointerLeave.bind(this)),
          n.includes('Complete') && this.addEventListener('complete', this._onComplete.bind(this));
      }
    }
    _cleanupStateMachineListeners() {
      le &&
        this._canvas instanceof HTMLCanvasElement &&
        (this._canvas.removeEventListener('pointerup', this._onPointerUp.bind(this)),
        this._canvas.removeEventListener('pointerdown', this._onPointerDown.bind(this)),
        this._canvas.removeEventListener('pointermove', this._onPointerMove.bind(this)),
        this._canvas.removeEventListener('pointerenter', this._onPointerEnter.bind(this)),
        this._canvas.removeEventListener('pointerleave', this._onPointerLeave.bind(this)),
        this.removeEventListener('complete', this._onComplete.bind(this)));
    }
    loadStateMachineData(n) {
      return this._dotLottieCore?.loadStateMachineData(n) ?? !1;
    }
    animationSize() {
      let n = this._dotLottieCore?.animationSize().get(0) ?? 0,
        a = this._dotLottieCore?.animationSize().get(1) ?? 0;
      return { width: n, height: a };
    }
    setStateMachineBooleanContext(n, a) {
      return this._dotLottieCore?.setStateMachineBooleanContext(n, a) ?? !1;
    }
    setStateMachineNumericContext(n, a) {
      return this._dotLottieCore?.setStateMachineNumericContext(n, a) ?? !1;
    }
    setStateMachineStringContext(n, a) {
      return this._dotLottieCore?.setStateMachineStringContext(n, a) ?? !1;
    }
  };
x(M, '_wasmModule', null);
var we = M;
var E = new Map(),
  $n = {
    ready: (s) => (n) => {
      let a = { id: '', method: 'onReady', result: { instanceId: s, event: n } };
      self.postMessage(a);
    },
    complete: (s) => (n) => {
      let a = { id: '', method: 'onComplete', result: { instanceId: s, event: n } };
      self.postMessage(a);
    },
    load: (s) => (n) => {
      let u = { id: '', method: 'onLoad', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    loadError: (s) => (n) => {
      let u = { id: '', method: 'onLoadError', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    loop: (s) => (n) => {
      let u = { id: '', method: 'onLoop', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    play: (s) => (n) => {
      let u = { id: '', method: 'onPlay', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    pause: (s) => (n) => {
      let u = { id: '', method: 'onPause', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    stop: (s) => (n) => {
      let u = { id: '', method: 'onStop', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    frame: (s) => (n) => {
      let u = { id: '', method: 'onFrame', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    render: (s) => (n) => {
      let u = { id: '', method: 'onRender', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    freeze: (s) => (n) => {
      let u = { id: '', method: 'onFreeze', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    unfreeze: (s) => (n) => {
      let u = { id: '', method: 'onUnfreeze', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
    destroy: (s) => (n) => {
      let u = { id: '', method: 'onDestroy', result: { instanceId: s, event: n } };
      self.postMessage(u);
    },
  },
  Ut = {
    getDotLottieInstanceState(s) {
      let n = s.params.instanceId,
        a = E.get(n);
      if (!a) throw new Error(`Instance with id ${n} does not exist.`);
      return {
        state: {
          isLoaded: a.isLoaded,
          isPaused: a.isPaused,
          isPlaying: a.isPlaying,
          isStopped: a.isStopped,
          isFrozen: a.isFrozen,
          loop: a.loop,
          mode: a.mode,
          speed: a.speed,
          currentFrame: a.currentFrame,
          totalFrames: a.totalFrames,
          duration: a.duration,
          useFrameInterpolation: a.useFrameInterpolation,
          renderConfig: a.renderConfig,
          marker: a.marker,
          backgroundColor: a.backgroundColor,
          markers: a.markers(),
          activeAnimationId: a.activeAnimationId,
          activeThemeId: a.activeThemeId,
          autoplay: a.autoplay,
          segment: a.segment,
          layout: a.layout,
          segmentDuration: a.segmentDuration,
          isReady: a.isReady,
          manifest: a.manifest,
        },
      };
    },
    setLayout(s) {
      let n = s.params.instanceId,
        a = s.params.layout,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      return u.setLayout(a), { success: !0 };
    },
    getStateMachineListeners(s) {
      let n = s.params.instanceId,
        a = E.get(n);
      if (!a) throw new Error(`Instance with id ${n} does not exist.`);
      return a.getStateMachineListeners();
    },
    postStateMachineEvent(s) {
      let n = s.params.instanceId,
        a = s.params.event,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      return u.postStateMachineEvent(a);
    },
    startStateMachine(s) {
      let n = s.params.instanceId,
        a = E.get(n);
      if (!a) throw new Error(`Instance with id ${n} does not exist.`);
      return a.startStateMachine();
    },
    stopStateMachine(s) {
      let n = s.params.instanceId,
        a = E.get(n);
      if (!a) throw new Error(`Instance with id ${n} does not exist.`);
      return a.stopStateMachine();
    },
    loadStateMachine(s) {
      let n = s.params.instanceId,
        a = s.params.stateMachineId,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      return u.loadStateMachine(a);
    },
    create: (s) => {
      let n = s.params.instanceId,
        a = s.params.config,
        u = s.params.width,
        w = s.params.height;
      if (E.has(n)) throw new Error(`Instance with id ${n} already exists.`);
      let T = new we(a);
      return (
        (T.canvas.height = w),
        (T.canvas.width = u),
        E.set(n, T),
        [
          'complete',
          'frame',
          'load',
          'loadError',
          'loop',
          'pause',
          'play',
          'stop',
          'destroy',
          'freeze',
          'unfreeze',
          'render',
          'ready',
        ].forEach((K) => {
          T.addEventListener(K, $n[K](n));
        }),
        { instanceId: n }
      );
    },
    destroy: (s) => {
      let n = s.params.instanceId,
        a = E.get(n);
      a && (a.destroy(), E.delete(n));
    },
    freeze: (s) => {
      let n = s.params.instanceId,
        a = E.get(n);
      if (!a) throw new Error(`Instance with id ${n} does not exist.`);
      a.freeze();
    },
    load: (s) => {
      let n = s.params.instanceId,
        a = s.params.config,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      u.load(a);
    },
    loadAnimation: (s) => {
      let n = s.params.instanceId,
        a = s.params.animationId,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      u.loadAnimation(a);
    },
    loadTheme: (s) => {
      let n = s.params.instanceId,
        a = s.params.themeId,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      return u.loadTheme(a);
    },
    loadThemeData: (s) => {
      let n = s.params.instanceId,
        a = s.params.themeData,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      return u.loadThemeData(a);
    },
    pause: (s) => {
      let n = s.params.instanceId,
        a = E.get(n);
      if (!a) throw new Error(`Instance with id ${n} does not exist.`);
      return a.pause();
    },
    play: (s) => {
      let n = s.params.instanceId,
        a = E.get(n);
      if (!a) throw new Error(`Instance with id ${n} does not exist.`);
      return a.play();
    },
    resize: (s) => {
      let n = s.params.instanceId,
        a = s.params.width,
        u = s.params.height,
        w = E.get(n);
      if (!w) throw new Error(`Instance with id ${n} does not exist.`);
      return (w.canvas.height = u), (w.canvas.width = a), w.resize(), { success: !0 };
    },
    setBackgroundColor: (s) => {
      let n = s.params.instanceId,
        a = s.params.backgroundColor,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      u.setBackgroundColor(a);
    },
    setFrame: (s) => {
      let n = s.params.instanceId,
        a = s.params.frame,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      u.setFrame(a);
    },
    setMode: (s) => {
      let n = s.params.instanceId,
        a = s.params.mode,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      u.setMode(a);
    },
    setRenderConfig: (s) => {
      let n = s.params.instanceId,
        a = s.params.renderConfig,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      u.setRenderConfig(a);
    },
    setSegment: (s) => {
      let n = s.params.instanceId,
        a = s.params.segment,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      u.setSegment(a[0], a[1]);
    },
    setSpeed: (s) => {
      let n = s.params.instanceId,
        a = s.params.speed,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      u.setSpeed(a);
    },
    setUseFrameInterpolation: (s) => {
      let n = s.params.instanceId,
        a = s.params.useFrameInterpolation,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      u.setUseFrameInterpolation(a);
    },
    setWasmUrl: (s) => {
      we.setWasmUrl(s.params.url);
    },
    stop: (s) => {
      let n = s.params.instanceId,
        a = E.get(n);
      if (!a) throw new Error(`Instance with id ${n} does not exist.`);
      a.stop();
    },
    unfreeze: (s) => {
      let n = s.params.instanceId,
        a = E.get(n);
      if (!a) throw new Error(`Instance with id ${n} does not exist.`);
      a.unfreeze();
    },
    setViewport(s) {
      let n = s.params.instanceId,
        a = s.params.x,
        u = s.params.y,
        w = s.params.width,
        T = s.params.height,
        B = E.get(n);
      if (!B) throw new Error(`Instance with id ${n} does not exist.`);
      return B.setViewport(a, u, w, T);
    },
    setMarker(s) {
      let n = s.params.instanceId,
        a = s.params.marker,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      return u.setMarker(a), { success: !0 };
    },
    setLoop(s) {
      let n = s.params.instanceId,
        a = s.params.loop,
        u = E.get(n);
      if (!u) throw new Error(`Instance with id ${n} does not exist.`);
      return u.setLoop(a), { success: !0 };
    },
  };
function kn(s) {
  let n = s.method;
  if (typeof Ut[n] == 'function') return Ut[n](s);
  throw new Error(`Method ${n} is not implemented in commands.`);
}
self.onmessage = (s) => {
  try {
    let n = kn(s.data),
      a = { id: s.data.id, method: s.data.method, result: n };
    self.postMessage(a);
  } catch (n) {
    let a = { id: s.data.id, method: s.data.method, error: n.message };
    self.postMessage(a);
  }
};
var Dn = '',
  lr = Dn;

export { lr as default };
