name: Deploy Viewer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/viewer/**'
      - 'packages/web/**'

concurrency:
  group: deploy-viewer
  cancel-in-progress: true

permissions: {}

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.repository == 'LottieFiles/dotlottie-web'

    permissions:
      contents: write
      pages: write

    steps:
      - name: 🛡 Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: ⬇️ Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: ⎔ Setup pnpm@v10
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: ⎔ Setup Node@lts
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version: lts/*

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: 🏗 Build
        run: pnpm build --filter='viewer...'

      - name: 🌐 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/viewer/dist
